// ==================== ALBUM (motor de reflexión) ====================
// Este juego usa js/motor-reflexion.js — acá sólo va su configuración.
// Banco expandido a 100 consignas.
window.CONFIG_REFLEXION = window.CONFIG_REFLEXION || {};
window.CONFIG_REFLEXION['album'] = {
    "tipo": "texto",
    "mensajePostRevelado": "Si esta respuesta fuera una fotografía, ¿qué veríamos? 📸",
    "instrucciones": "Describan una escena sin mostrarla hasta que ambos terminen. Queda guardada como una foto invisible.",
    "banco": [
        "Un momento conmigo que guardarías para siempre.",
        "Una escena de nuestros días juntos que repetirías tal cual fue.",
        "Un lugar al que te gustaría llevarme algún día.",
        "Una imagen (real o inventada) que representa nuestra relación.",
        "Un instante cotidiano que se sintió especial sin motivo aparente.",
        "Cómo te imaginás el día que finalmente vivamos juntos.",
        "Una escena que te gustaría que alguien pintara de nosotros.",
        "El momento exacto en el que sentiste que esto era serio.",
        "Una foto que te gustaría que existiera de nosotros, aunque no exista.",
        "Una escena de un reencuentro futuro, tal como te la imaginás.",
        "Un atardecer o amanecer que te gustaría vivir conmigo.",
        "Una escena cotidiana de una casa futura, imaginada con detalle.",
        "Un momento en el que sentiste que el tiempo se detenía.",
        "Una escena de nosotros riéndonos de algo tonto.",
        "Un lugar de tu ciudad que te gustaría fotografiar conmigo algún día.",
        "Una escena de comida compartida, real o imaginada, que te gusta pensar.",
        "Un momento de silencio compartido que fue lindo, no incómodo.",
        "Una escena de nosotros bailando, aunque sea mal.",
        "Un momento en el que te sentiste completamente vos mismo/a conmigo.",
        "Una escena que te gustaría enmarcar y colgar en nuestra futura casa.",
        "Un instante de ternura que recordás con claridad.",
        "Una escena imaginada de nosotros de viejos, juntos.",
        "Un momento en el que el otro te hizo sentir seguro/a.",
        "Una escena de un viaje futuro que te gustaría vivir conmigo.",
        "Un instante en el que sentiste orgullo del otro.",
        "Una escena de una discusión que terminó en abrazo.",
        "Un momento en una videollamada que se sintió como estar en persona.",
        "Una escena imaginada de presentarme (o presentarte) a tu familia.",
        "Un instante en el que la distancia se sintió más corta que nunca.",
        "Una escena de una mañana cualquiera que te gustaría vivir conmigo.",
        "Un momento donde el otro te hizo reír en medio de un mal día.",
        "Una escena imaginada de nuestra boda (aunque sea hipotética).",
        "Un instante donde sentiste gratitud pura por tenernos.",
        "Una escena de una noche estrellada que te gustaría compartir conmigo.",
        "Un momento donde uno cuidó al otro estando enfermo, aunque sea a la distancia.",
        "Una escena imaginada de la primera Navidad juntos en persona.",
        "Un instante donde sentiste que valía la pena todo el esfuerzo.",
        "Una escena de cocinar juntos, real o imaginada.",
        "Un momento donde uno sorprendió al otro sin aviso.",
        "Una escena imaginada de mudarnos juntos por primera vez.",
        "Un instante donde el otro te escuchó sin juzgar.",
        "Una escena de una caminata que te gustaría dar conmigo.",
        "Un momento donde sentiste que esto era diferente a todo lo anterior.",
        "Una escena imaginada de despertarnos juntos un domingo cualquiera.",
        "Un instante donde el otro te defendió o apoyó públicamente.",
        "Una escena de un festejo de cumpleaños, real o imaginado.",
        "Un momento donde el silencio dijo más que cualquier palabra.",
        "Una escena imaginada de una pelea de almohadas o algo igual de tonto.",
        "Un instante donde sentiste que esto iba a durar mucho tiempo.",
        "Una escena de nosotros mirando una serie o película juntos.",
        "Un momento donde el otro te hizo sentir menos solo/a.",
        "Una escena imaginada de un picnic en algún lugar bonito.",
        "Un instante donde te reíste tanto que te dolió la panza.",
        "Una escena de una charla profunda a la luz de las velas (real o imaginada).",
        "Un momento donde el otro dijo exactamente lo que necesitabas escuchar.",
        "Una escena imaginada de recibirme (o recibirte) en el aeropuerto.",
        "Un instante donde sentiste una conexión total sin decir nada.",
        "Una escena de nosotros bajo la lluvia, real o imaginada.",
        "Un momento donde el otro te hizo un gesto pequeño pero significativo.",
        "Una escena imaginada de una cena especial que nos gustaría vivir.",
        "Un instante donde te sentiste profundamente amado/a.",
        "Una escena de un abrazo que se sintió eterno.",
        "Un momento donde ambos nos reímos de un mal entendido, después de aclararlo.",
        "Una escena imaginada de un viaje en auto largo, escuchando música juntos.",
        "Un instante donde sentiste alivio de poder contarme algo difícil.",
        "Una escena de nosotros escribiéndonos cartas a mano, real o imaginada.",
        "Un momento donde el otro celebró un logro tuyo como si fuera propio.",
        "Una escena imaginada de nuestra primera Navidad con nuestra futura familia.",
        "Un instante donde sentiste que este amor te hacía mejor persona.",
        "Una escena de un juego o competencia tonta entre nosotros.",
        "Un momento donde uno esperó pacientemente al otro sin quejarse.",
        "Una escena imaginada de festejar un aniversario número diez.",
        "Un instante donde te sorprendió lo bien que me/te conocés a esta altura.",
        "Una escena de nosotros armando planes en una libreta o pizarra.",
        "Un momento donde sentiste que podías mostrar tu peor versión sin miedo.",
        "Una escena imaginada de un festejo sorpresa que te gustaría organizar.",
        "Un instante donde el otro te hizo sentir en casa, aunque estuviéramos lejos.",
        "Una escena de despedirnos en una terminal o aeropuerto, con toda la emoción.",
        "Un momento donde entendiste algo nuevo sobre el amor gracias a nosotros.",
        "Una escena imaginada de nuestra rutina diaria si viviéramos juntos.",
        "Un instante donde sentiste que la espera valía absolutamente la pena.",
        "Una escena de nosotros discutiendo sobre algo sin importancia y riéndonos después.",
        "Un momento donde el otro te hizo sentir escuchado/a de verdad.",
        "Una escena imaginada de un festejo de Año Nuevo juntos.",
        "Un instante donde sentiste que esto era 'para siempre', aunque sea por un segundo.",
        "Una escena de nosotros mirando fotos viejas juntos, ya siendo grandes.",
        "Un momento donde ambos coincidimos exactamente en lo mismo sin hablarlo.",
        "Una escena imaginada de nuestra casa con nuestras cosas mezcladas.",
        "Un instante donde el otro te sorprendió con algo que recordaba de una charla vieja.",
        "Una escena de festejar algo chiquito, como si fuera enorme.",
        "Un momento donde te diste cuenta de cuánto creciste gracias a esta relación.",
        "Una escena imaginada de un finde entero sin planes, sólo estando juntos.",
        "Un instante donde sentiste que ya no había vuelta atrás, y eso te dio paz.",
        "Una escena de nosotros mandándonos fotos random del día a día.",
        "Un momento donde el otro te hizo reír en el peor momento posible.",
        "Una escena imaginada de contarle a nuestros nietos cómo empezó todo.",
        "Un instante donde entendiste que este amor era distinto porque elegís, no porque es fácil.",
        "Una escena final, la que te gustaría que cerrara nuestra historia, mucho tiempo después.",
        "Una escena imaginada de despertarnos abrazados sin necesidad de despertador.",
        "Un instante donde sentiste que ya éramos, sin dudas, un equipo."
    ]
};
