// ==================== BATALLA DE CANCIONES (motor de reflexión) ====================
window.CONFIG_REFLEXION = window.CONFIG_REFLEXION || {};
window.CONFIG_REFLEXION['batallacanciones'] = {
    tipo: 'texto',
    placeholder: 'Nombre de la canción y artista...',
    mensajePostRevelado: '¿Cuál te gustó más? Se lo dicen en el chat 😉',
    instrucciones: 'Sale un tema. Cada uno escribe una canción que le calce (nombre y artista). Se revela junto — sin puntaje, sólo para descubrir gustos.',
    banco: [
        'Una canción triste',
        'Una que te haga bailar sin poder evitarlo',
        'Una canción para manejar de noche',
        'Una que te haga acordar a tu infancia',
        'Una canción perfecta para una lluvia',
        'Una que pondrías en nuestra playlist de pareja',
        'Una canción con la que llorarías sin vergüenza',
        'Una que te levanta el ánimo siempre',
        'Una canción para bailar pegados',
        'Una que te haga acordar a un verano',
        'Una canción que no le mostrarías a nadie',
        'Una que cantarías a los gritos en el auto',
        'Una canción para una despedida',
        'Una que te gustaría que suene en tu boda',
        'Una canción de una banda o artista under',
        'Una que hable de extrañar a alguien',
        'Una canción de tu adolescencia que todavía te gusta',
        'Una que asocies con un lugar específico',
        'Una canción para relajarse después de un mal día',
        'Una que te sabés de memoria, letra completa',
        'Una canción que descubriste hace poco',
        'Una que te gustaría bailar lento con alguien',
        'Una canción con una letra que te parece hermosa',
        'Una que te haga sentir valiente',
        'Una canción para un domingo de lluvia',
        'Una que asocies con un recuerdo feliz',
        'Una canción que odiás pero no podés dejar de escuchar',
        'Una que le pondrías a una escena de película',
        'Una canción para festejar algo grande',
        'Una que te gustaría que alguien te dedique',
    ]
};
