// ==================== COMPLETÁ LA FRASE (motor de reflexión) ====================
// Este juego usa js/motor-reflexion.js — acá sólo va su configuración.
// Una frase empezada, cada uno la completa a solas y se revelan juntas.
// 60 frases.
window.CONFIG_REFLEXION = window.CONFIG_REFLEXION || {};
window.CONFIG_REFLEXION['completafrase'] = {
    tipo: 'texto',
    nombreJuego: 'Completá la Frase',
    botonNuevo: 'Nueva frase',
    placeholder: 'Completala a tu manera…',
    instrucciones: 'Una frase empezada: cada uno la completa a solas y se revelan juntas.',
    mensajePostRevelado: '💛 ¿Se esperaban lo que escribió el otro?',
    banco: [
    "Lo que más me gusta de vos cuando nadie nos ve es…",
    "Me di cuenta de que te quería cuando…",
    "Si tuviéramos un día entero sin obligaciones, me gustaría…",
    "Una canción que me hace pensar en vos es… porque…",
    "Me siento más cerca tuyo cuando…",
    "Algo que nunca te dije pero pienso seguido es…",
    "Si nuestra relación fuera una película, se llamaría…",
    "Lo más gracioso que hiciste sin darte cuenta fue…",
    "Me encanta cuando me decís…",
    "Un lugar al que quiero llevarte algún día es…",
    "El mejor regalo que me podrías hacer no cuesta plata y es…",
    "Cuando estoy triste, lo que más me ayuda de vos es…",
    "Si pudiera revivir un día con vos, elegiría…",
    "Una costumbre tuya que me da ternura es…",
    "Me hace reír cuando vos…",
    "Algo que aprendí gracias a vos es…",
    "Nuestro plan perfecto de domingo sería…",
    "Si te tuviera que describir en tres palabras, serían…",
    "Lo que más admiro de vos es…",
    "Una vez me sorprendiste cuando…",
    "Me gustaría que juntos aprendiéramos a…",
    "El primer recuerdo que tengo de vos es…",
    "Si pudiera darte un superpoder, te daría…",
    "Un miedo que se me va cuando estoy con vos es…",
    "La comida que siempre me va a recordar a vos es…",
    "Algo que me gustaría que hiciéramos más seguido es…",
    "Me sentí muy orgulloso/a de vos cuando…",
    "Si escribiera un libro sobre nosotros, el primer capítulo empezaría…",
    "Lo que más extraño cuando no estamos juntos es…",
    "Una cosa que me encanta de cómo me mirás es…",
    "En diez años me imagino que un día normal nuestro sería…",
    "Me da paz cuando vos…",
    "Si fueras un animal, serías… porque…",
    "La palabra que mejor nos describe como pareja es…",
    "Un sueño que quiero cumplir con vos es…",
    "Me encanta tu forma de…",
    "El mejor consejo que me diste fue…",
    "Si pudiera pedir un deseo para los dos, pediría…",
    "Una tradición que me gustaría inventar juntos es…",
    "Me puse nervioso/a con vos la vez que…",
    "Lo que más me gusta de nuestras charlas es…",
    "Si tuviera que elegir una foto nuestra para enmarcar, sería…",
    "Algo tuyo que al principio no entendía y ahora me encanta es…",
    "Me siento cuidado/a cuando…",
    "La mejor sorpresa que podría darte sería…",
    "Un olor que me recuerda a vos es…",
    "Si pudiéramos vivir en cualquier época, elegiría… porque…",
    "Algo que quiero agradecerte hoy es…",
    "Lo más lindo que alguien me dijo de vos fue…",
    "Si nuestra relación tuviera un lema, sería…",
    "Mi momento favorito del día con vos es…",
    "Una cosa chiquita que hacés y me cambia el día es…",
    "Si pudiera mostrarte algo de mi infancia, te mostraría…",
    "Me encantaría que me enseñaras a…",
    "Lo primero que pienso cuando me despierto a tu lado es…",
    "Una pelea que nos hizo más fuertes fue…",
    "El viaje que más quiero hacer con vos es a… porque…",
    "Si fueras una estación del año, serías… porque…",
    "La versión de mí que aparece cuando estoy con vos es…",
    "Algo que nunca quiero que cambie entre nosotros es…"
]
};
