// ==================== DETECTIVE (motor de reflexión) ====================
// Este juego usa js/motor-reflexion.js — acá sólo va su configuración.
// Banco expandido a 101 consignas.
window.CONFIG_REFLEXION = window.CONFIG_REFLEXION || {};
window.CONFIG_REFLEXION['detective'] = {
    "tipo": "texto",
    "instrucciones": "Una pista sobre un momento nuestro. Adivinen quién, cuándo y qué estaba pasando — todo junto en una respuesta.",
    "banco": [
        "Pista: uno de los dos dijo algo que el otro no esperaba, muy al principio de todo. ¿Quién lo dijo, más o menos cuándo, y qué estaba pasando?",
        "Pista: hubo un mensaje que cambió el tono de la conversación entre nosotros. ¿Quién lo mandó y en qué contexto?",
        "Pista: en algún momento uno de los dos tuvo miedo de arruinar todo. ¿Quién, cuándo y por qué?",
        "Pista: hubo una primera vez que uno de los dos dijo 'te quiero' o algo parecido. ¿Quién, cuándo, cómo fue?",
        "Pista: en nuestros días juntos hubo un momento incómodo que después se volvió gracioso. ¿Cuál fue?",
        "Pista: alguno de los dos casi cancela un plan importante. ¿Quién, cuándo, por qué no lo hizo?",
        "Pista: hubo una charla difícil que terminó acercándonos más. ¿Cuándo fue y de qué se trataba?",
        "Pista: en algún momento uno se dio cuenta de que esto iba en serio. ¿Quién, cuándo, qué lo disparó?",
        "Pista: hubo un chiste interno que nació de una situación puntual. ¿Cuál fue el origen?",
        "Pista: uno de los dos tuvo que tomar una decisión difícil por esta relación. ¿Quién y cuál fue?",
        "Pista: hubo una noche en la que hablamos hasta muy tarde sin darnos cuenta del horario. ¿De qué hablamos?",
        "Pista: alguno de los dos se puso celoso alguna vez. ¿Quién, por qué situación?",
        "Pista: hubo una foto o video que se volvió especial entre nosotros. ¿Cuál y por qué?",
        "Pista: en algún momento discutimos por un mal entendido tonto. ¿Cuál fue?",
        "Pista: uno de los dos hizo un gesto inesperado que sorprendió al otro. ¿Cuál fue?",
        "Pista: hubo un día en que uno estaba mal y el otro lo notó sin que se lo dijeran. ¿Cuándo fue?",
        "Pista: en algún momento hablamos de nuestro pasado sentimental. ¿Cómo fue esa charla?",
        "Pista: hubo una vez que uno mintió, aunque sea una mentira piadosa. ¿Sobre qué?",
        "Pista: alguno de los dos propuso algo arriesgado para la relación. ¿Qué fue?",
        "Pista: hubo un momento donde sentimos que 'esto es distinto' por primera vez. ¿Cuándo?",
        "Pista: uno de los dos cambió de planes importantes por el otro. ¿Quién y qué cambió?",
        "Pista: hubo una charla sobre el futuro que nos dio miedo e ilusión a la vez. ¿De qué se trataba?",
        "Pista: alguna vez uno tuvo que defender esta relación frente a otra persona. ¿Cuándo y ante quién?",
        "Pista: hubo un día que sentimos la distancia más pesada que nunca. ¿Cuándo fue y qué pasó?",
        "Pista: uno de los dos hizo algo para sorprender al otro sin avisar. ¿Qué fue?",
        "Pista: hubo una charla donde hablamos de nuestros defectos sin pelear. ¿De qué hablamos?",
        "Pista: alguno de los dos dudó de la relación en algún momento. ¿Quién, cuándo, por qué?",
        "Pista: hubo un momento donde entendimos que nos hacíamos bien mutuamente. ¿Cuándo?",
        "Pista: uno de los dos lloró de emoción por algo que dijo o hizo el otro. ¿Qué fue?",
        "Pista: hubo una vez que discutimos por celos, reales o imaginarios. ¿Sobre qué?",
        "Pista: alguno propuso una tradición o costumbre nuestra que sigue hasta hoy. ¿Cuál y quién la propuso?",
        "Pista: hubo un momento donde uno pidió disculpas primero, sin que se lo pidieran. ¿Cuándo?",
        "Pista: uno de los dos hizo algo valiente por esta relación. ¿Qué fue?",
        "Pista: hubo una charla sobre celos o inseguridades que terminó bien. ¿De qué hablamos?",
        "Pista: alguno de los dos tuvo que elegir entre algo importante y esta relación. ¿Qué eligió y qué pasó?",
        "Pista: hubo un día random que terminó siendo memorable sin planearlo. ¿Cuándo y qué pasó?",
        "Pista: uno de los dos confesó un miedo que nunca había dicho antes. ¿Cuál fue?",
        "Pista: hubo una charla sobre mudarnos juntos que nos ilusionó mucho. ¿Cuándo fue?",
        "Pista: alguno de los dos dijo algo gracioso que se volvió parte de nuestro vocabulario. ¿Qué fue?",
        "Pista: hubo un momento donde sentimos que estábamos totalmente en la misma sintonía. ¿Cuándo?",
        "Pista: uno de los dos tomó la iniciativa en un momento clave de la relación. ¿Cuál fue ese momento?",
        "Pista: uno de los dos aprendió una palabra o frase del idioma/dialecto del otro. ¿Cuál fue y en qué contexto?",
        "Pista: hubo una comida o bebida que probamos juntos (o describimos) por primera vez. ¿Cuál fue?",
        "Pista: alguno de los dos armó un plan sorpresa para el otro, aunque sea chico. ¿Cuál fue?",
        "Pista: hubo una canción que empezó a sonar en un momento importante. ¿Cuál fue y qué pasaba?",
        "Pista: uno de los dos tuvo que pedir perdón por algo que dijo sin pensar. ¿Sobre qué fue?",
        "Pista: hubo una vez que uno se quedó dormido/a en medio de una llamada. ¿Quién y cuándo?",
        "Pista: alguno mencionó por primera vez la palabra 'futuro' hablando de nosotros. ¿Quién y cuándo?",
        "Pista: hubo un día en que ambos coincidimos en algo sin hablarlo antes. ¿Qué fue?",
        "Pista: uno de los dos compartió algo vergonzoso de su pasado. ¿Qué fue, más o menos?",
        "Pista: hubo una charla sobre qué haríamos si algo saliera mal entre nosotros. ¿Cuándo fue?",
        "Pista: alguno de los dos armó una lista de cosas para hacer cuando se vean. ¿Quién y qué tenía la lista?",
        "Pista: hubo un momento donde uno defendió una opinión distinta a la del otro, con respeto. ¿Sobre qué tema?",
        "Pista: uno de los dos mandó un audio largo contando algo importante. ¿De qué se trataba?",
        "Pista: hubo una vez que planeamos algo y no salió como esperábamos, pero terminó bien igual. ¿Qué fue?",
        "Pista: alguno confesó qué fue lo que más le costó de empezar esta relación. ¿Qué dijo?",
        "Pista: hubo un día en que uno estuvo más callado de lo normal y el otro lo notó. ¿Qué pasaba?",
        "Pista: uno de los dos compartió una meta personal grande con el otro por primera vez. ¿Cuál fue?",
        "Pista: hubo una charla donde hablamos de qué esperamos de una pelea. ¿Qué acordamos?",
        "Pista: alguno mencionó a un ex de forma natural, sin incomodidad. ¿En qué contexto?",
        "Pista: hubo un momento donde sentimos vergüenza juntos por algo gracioso. ¿Qué pasó?",
        "Pista: uno de los dos investigó algo sobre la cultura o ciudad del otro sin que se lo pidieran. ¿Qué investigó?",
        "Pista: hubo una charla sobre qué significa para cada uno la palabra 'compromiso'. ¿Qué se dijo?",
        "Pista: alguno propuso ver la misma película o serie al mismo tiempo, aunque estuviéramos lejos. ¿Cuál fue?",
        "Pista: hubo un día en que uno canceló otro plan para priorizar hablar con el otro. ¿Quién y por qué?",
        "Pista: uno de los dos mencionó por primera vez el miedo a que esto no funcione. ¿Cómo se resolvió esa charla?",
        "Pista: hubo una vez que ambos coincidimos en un sueño o meta para el futuro. ¿Cuál fue?",
        "Pista: alguno se disculpó por algo que hizo mucho antes de esta relación. ¿Qué fue?",
        "Pista: hubo un momento donde uno se sintió muy orgulloso del logro del otro. ¿Cuál fue el logro?",
        "Pista: uno de los dos compartió su comida favorita de la infancia. ¿Cuál fue?",
        "Pista: hubo una charla sobre qué es lo que más valoramos de la familia del otro. ¿Qué se dijo?",
        "Pista: alguno de los dos mandó una nota de voz cantando, aunque sea mal. ¿Cuándo pasó?",
        "Pista: hubo un día donde ambos admitimos que extrañábamos algo muy específico del otro. ¿Qué era?",
        "Pista: uno de los dos contó un secreto que nunca le había contado a nadie más. ¿Qué tipo de secreto era?",
        "Pista: hubo una charla sobre qué haríamos el primer día que estemos juntos sin límite de tiempo. ¿Qué se dijo?",
        "Pista: alguno propuso una regla o acuerdo para la relación que seguimos hoy. ¿Cuál fue?",
        "Pista: hubo un momento donde uno agradeció al otro por algo muy específico. ¿Qué fue?",
        "Pista: uno de los dos compartió una foto vieja de su infancia por primera vez. ¿Qué mostraba?",
        "Pista: hubo una charla sobre qué tan distintas son nuestras rutinas diarias. ¿Qué descubrimos?",
        "Pista: alguno mencionó por primera vez que pensaba en mudarse por el otro. ¿Cuándo fue?",
        "Pista: hubo un día donde discutimos por horarios o zonas horarias. ¿Cómo se resolvió?",
        "Pista: uno de los dos hizo una promesa chiquita que cumplió sin que se lo recordaran. ¿Cuál fue?",
        "Pista: hubo una charla sobre qué tan reales se sienten las videollamadas comparadas con estar en persona. ¿Qué se dijo?",
        "Pista: alguno confesó que a veces mira fotos viejas nuestras cuando extraña al otro. ¿Cuál fue la charla?",
        "Pista: hubo un momento donde ambos coincidimos en que 'esto vale la pena', en voz alta. ¿Cuándo fue?",
        "Pista: uno de los dos aprendió a cocinar algo pensando en el otro. ¿Qué plato fue?",
        "Pista: hubo una charla sobre los primeros días, comparando cómo cada uno vivió el inicio de esto. ¿Qué se descubrió?",
        "Pista: alguno mencionó una canción que le hace acordar al otro sin razón aparente. ¿Cuál fue?",
        "Pista: hubo un momento donde uno tuvo que elegir entre salir con amigos o hablar con el otro. ¿Qué eligió?",
        "Pista: uno de los dos armó una sorpresa por correo o delivery para el otro. ¿Qué mandó?",
        "Pista: hubo una charla profunda sobre qué haríamos si el otro cambiara mucho con el tiempo. ¿Qué se dijo?",
        "Pista: alguno confesó que guarda mensajes viejos para releerlos en días difíciles. ¿Cuáles suele releer?",
        "Pista: hubo un día donde ambos coincidimos en estar tristes por la misma razón, sin saberlo antes. ¿Cuál fue?",
        "Pista: uno de los dos organizó algo especial para una fecha importante, aunque fuera a la distancia. ¿Qué fue?",
        "Pista: hubo una charla sobre qué tanto confiamos en el otro comparado al principio. ¿Qué cambió?",
        "Pista: alguno mencionó por primera vez a la familia del otro con cariño genuino. ¿Cuándo fue?",
        "Pista: hubo un momento donde discutimos por celos de una red social. ¿Cómo se resolvió?",
        "Pista: uno de los dos guardó un objeto que le recuerda al otro. ¿Cuál es ese objeto?",
        "Pista: hubo una charla sobre qué tan parecidos somos en la forma de enojarnos. ¿Qué descubrimos?",
        "Pista: alguno propuso festejar algo random un día cualquiera, sin motivo especial. ¿Qué festejamos?",
        "Pista: hubo un momento donde ambos dijimos la misma frase al mismo tiempo. ¿Cuál fue, o qué tipo de frase?"
    ]
};
