// ==================== FUTURO (motor de reflexión) ====================
// Este juego usa js/motor-reflexion.js — acá sólo va su configuración.
// Banco expandido a 100 consignas.
window.CONFIG_REFLEXION = window.CONFIG_REFLEXION || {};
window.CONFIG_REFLEXION['futuro'] = {
    "tipo": "texto",
    "instrucciones": "Rondas imaginando cómo se ven juntos más adelante. Se revela todo junto.",
    "banco": [
        "¿Dónde te gustaría que viviéramos en unos años?",
        "¿Cómo sería una noche cualquiera dentro de 5 años, para vos?",
        "¿Qué hábito deberíamos construir juntos desde ya?",
        "¿Qué aventura grande deberíamos vivir alguna vez?",
        "¿Qué cosa de lo que tenemos hoy jamás deberíamos perder?",
        "¿Cómo te imaginás nuestros domingos en el futuro?",
        "¿Qué tipo de familia o vida en común te imaginás?",
        "¿Qué tradición nueva te gustaría que empecemos?",
        "¿Cómo nos imaginás discutiendo (si es que discutimos) en el futuro?",
        "¿Qué versión de nosotros te gustaría ver dentro de 10 años?",
        "¿Cómo te gustaría que fuera nuestra casa dentro de 5 años?",
        "¿Qué trabajo o proyecto te gustaría estar haciendo en el futuro?",
        "¿Cómo te imaginás nuestras vacaciones ideales dentro de unos años?",
        "¿Qué te gustaría que la gente dijera de nosotros como pareja en el futuro?",
        "¿Cómo te imaginás celebrando nuestro décimo aniversario?",
        "¿Qué proyecto en común te gustaría empezar el año que viene?",
        "¿Cómo te gustaría que fueran nuestras mañanas si viviéramos juntos?",
        "¿Qué lugar del mundo te gustaría que sea 'nuestro' con el tiempo?",
        "¿Cómo te imaginás pasando las fiestas de fin de año en el futuro?",
        "¿Qué te gustaría que aprendiéramos juntos en los próximos años?",
        "¿Cómo te imaginás nuestra rutina de fin de semana ideal, más adelante?",
        "¿Qué te gustaría que fuera distinto en nosotros dentro de un año?",
        "¿Cómo te imaginás nuestra comunicación cuando ya no haya distancia?",
        "¿Qué costumbre de tu familia te gustaría traer a nuestra futura vida juntos?",
        "¿Cómo te imaginás nuestra mascota ideal, si tuviéramos una?",
        "¿Qué te gustaría lograr como equipo en los próximos 3 años?",
        "¿Cómo te imaginás nuestro primer departamento juntos?",
        "¿Qué actividad te gustaría que hagamos juntos todas las semanas en el futuro?",
        "¿Cómo te imaginás nuestras conversaciones dentro de 20 años?",
        "¿Qué te gustaría que supiéramos hacer juntos que hoy no sabemos?",
        "¿Cómo te imaginás festejando un logro grande de alguno de los dos, en el futuro?",
        "¿Qué te gustaría que representara nuestra casa cuando la tengamos?",
        "¿Cómo te imaginás pasando un día de enfermedad, cuidándonos mutuamente en persona?",
        "¿Qué te gustaría enseñarme en el futuro que hoy no sé?",
        "¿Cómo te imaginás nuestro círculo de amigos en común dentro de unos años?",
        "¿Qué te gustaría que digamos siempre, como frase propia de nosotros?",
        "¿Cómo te imaginás nuestras discusiones resueltas en el futuro, comparadas con hoy?",
        "¿Qué te gustaría construir juntos que no sea material?",
        "¿Cómo te imaginás el día que finalmente vivamos en la misma ciudad?",
        "¿Qué costumbre nueva te gustaría empezar el día que estemos juntos definitivamente?",
        "¿Cómo te imaginás nuestras conversaciones sobre el futuro dentro de 5 años, comparadas con hoy?",
        "¿Qué te gustaría que hiciéramos juntos por primera vez el año que viene?",
        "¿Cómo te imaginás nuestro equipo frente a una crisis futura?",
        "¿Qué tipo de padres (si algún día lo somos) te gustaría que seamos?",
        "¿Cómo te imaginás nuestras charlas de sobremesa dentro de 10 años?",
        "¿Qué te gustaría que valoremos más con el paso del tiempo?",
        "¿Cómo te imaginás nuestra forma de festejar los pequeños logros del día a día, en el futuro?",
        "¿Qué te gustaría que sea innegociable en nuestra vida juntos, pase lo que pase?",
        "¿Cómo te imaginás nuestras vacaciones cuando ya no tengamos que ahorrar para los pasajes?",
        "¿Qué te gustaría que fuera parte de nuestra rutina diaria en el futuro?",
        "¿Cómo te imaginás cuidándonos mutuamente cuando seamos grandes?",
        "¿Qué te gustaría que aprendamos el uno del otro con el tiempo?",
        "¿Cómo te imaginás nuestra primera pelea después de vivir juntos, y cómo la resolvemos?",
        "¿Qué te gustaría que fuera distinto de tu vida actual, gracias a nosotros, en 5 años?",
        "¿Cómo te imaginás celebrando un cumpleaños tuyo dentro de 10 años?",
        "¿Qué te gustaría que hiciéramos juntos los domingos de lluvia, en el futuro?",
        "¿Cómo te imaginás nuestra vida social como pareja, más adelante?",
        "¿Qué te gustaría que representemos como pareja para la gente que nos rodea?",
        "¿Cómo te imaginás nuestro primer viaje largo juntos, sin límite de presupuesto?",
        "¿Qué te gustaría que fuera parte de nuestra decoración en la futura casa?",
        "¿Cómo te imaginás resolviendo decisiones grandes de dinero en el futuro?",
        "¿Qué te gustaría que aprendiéramos a cocinar juntos con el tiempo?",
        "¿Cómo te imaginás nuestras noches de películas dentro de unos años?",
        "¿Qué te gustaría que fuera nuestra 'canción' oficial de acá a un tiempo?",
        "¿Cómo te imaginás celebrando el día que finalmente no haya más distancia?",
        "¿Qué te gustaría que hagamos juntos una vez al año, sin falta, para siempre?",
        "¿Cómo te imaginás nuestras conversaciones sobre tener hijos, en el futuro?",
        "¿Qué te gustaría que fuera un ritual exclusivo nuestro, con el tiempo?",
        "¿Cómo te imaginás apoyándonos en un momento difícil, dentro de unos años?",
        "¿Qué te gustaría que hiciéramos distinto la próxima vez que discutamos?",
        "¿Cómo te imaginás nuestras charlas filosóficas dentro de 15 años?",
        "¿Qué te gustaría que fuera parte de nuestra identidad como pareja, siempre?",
        "¿Cómo te imaginás enseñándole algo tuyo a nuestro futuro entorno (hijos, sobrinos, etc.)?",
        "¿Qué te gustaría lograr individualmente, sabiendo que voy a estar ahí para apoyarte?",
        "¿Cómo te imaginás nuestras rutinas de autocuidado compartidas en el futuro?",
        "¿Qué te gustaría que aprendamos sobre comunicación con el paso de los años?",
        "¿Cómo te imaginás celebrando nuestros 25 años juntos, si llegamos ahí?",
        "¿Qué te gustaría que hiciéramos la primera semana que vivamos juntos?",
        "¿Cómo te imaginás nuestro balance entre trabajo y tiempo juntos, en el futuro?",
        "¿Qué te gustaría que sea distinto en la forma en que nos cuidamos, con el tiempo?",
        "¿Cómo te imaginás pasando una Navidad o Año Nuevo con las dos familias juntas?",
        "¿Qué te gustaría que representemos para las próximas generaciones de nuestra familia?",
        "¿Cómo te imaginás nuestro primer gran desacuerdo importante ya viviendo juntos?",
        "¿Qué te gustaría que fuera parte de nuestros hobbies compartidos, en el futuro?",
        "¿Cómo te imaginás apoyándome en un proyecto grande mío, más adelante?",
        "¿Qué te gustaría que sintamos al mirar atrás, dentro de 10 años, sobre esta etapa de distancia?",
        "¿Cómo te imaginás nuestras conversaciones cuando ya no haya nada que ocultar ni explicar?",
        "¿Qué te gustaría que aprendiéramos a soltar, con el tiempo?",
        "¿Cómo te imaginás nuestro primer 'hogar' de verdad, sea donde sea?",
        "¿Qué te gustaría que perdure de nosotros, pase lo que pase en el futuro?",
        "¿Cómo te imaginás la primera vez que alguien nos pregunte 'hace cuánto están juntos' y contemos toda la historia?",
        "¿Qué te gustaría lograr juntos que hoy parece imposible?",
        "¿Cómo te imaginás nuestras charlas sobre el pasado, dentro de muchos años?",
        "¿Qué te gustaría que fuera un símbolo de esta etapa a distancia, en el futuro?",
        "¿Cómo te imaginás cuidando de mí en un momento de mucho estrés, más adelante?",
        "¿Qué te gustaría construir juntos que dure más que nosotros?",
        "¿Cómo te imaginás la primera Navidad que pasemos juntos, en persona?",
        "¿Qué te gustaría que aprenda de vos en los próximos años?",
        "¿Cómo te imaginás nuestra vida cuando ya no tengamos que contar los días para vernos?",
        "¿Qué te gustaría agradecerle a esta etapa de distancia, mirando hacia atrás en el futuro?"
    ]
};
