// ==================== MAQUINATIEMPO (motor de reflexión) ====================
// Este juego usa js/motor-reflexion.js — acá sólo va su configuración.
// Banco expandido a 101 consignas.
window.CONFIG_REFLEXION = window.CONFIG_REFLEXION || {};
window.CONFIG_REFLEXION['maquinatiempo'] = {
    "tipo": "texto",
    "mensajePostRevelado": "¿Tienen el mismo recuerdo en la cabeza? 💫",
    "instrucciones": "Elijan un momento de nuestra historia y cuenten qué recuerdan de él. Se revela junto.",
    "banco": [
        "Contá cómo recordás nuestro primer mensaje.",
        "Contá cómo recordás nuestro primer encuentro en persona.",
        "Contá cuál fue tu momento favorito juntos, y por qué.",
        "Contá cuál fue el momento más difícil que atravesamos juntos.",
        "Contá qué momento repetirías exactamente igual si pudieras.",
        "Contá qué momento cambiarías si pudieras, y cómo.",
        "Contá cómo recordás la primera vez que te dije 'te quiero' (o algo parecido).",
        "Contá cómo recordás nuestra primera videollamada larga.",
        "Contá cómo recordás el día que decidimos ponerle nombre a esto.",
        "Contá cómo recordás la primera vez que discutimos en serio.",
        "Contá cómo recordás la primera vez que te presenté (o me presentaste) a tu familia o amigos.",
        "Contá cómo recordás el día que hablamos de un futuro juntos por primera vez.",
        "Contá cómo recordás la despedida de nuestro primer encuentro en persona.",
        "Contá cómo recordás la primera semana después de conocernos.",
        "Contá cómo recordás el momento en que sentiste que esto iba en serio.",
        "Contá cómo recordás una noche cualquiera de charla que se hizo larga sin darnos cuenta.",
        "Contá cómo recordás el día que superamos un mal entendido grande.",
        "Contá cómo recordás la primera vez que lloraste (de alegría o de tristeza) por nosotros.",
        "Contá cómo recordás el primer regalo que nos hicimos.",
        "Contá cómo recordás la primera vez que dijimos 'te extraño' en serio.",
        "Contá cómo recordás un momento en el que sentiste que el otro te entendía sin explicar nada.",
        "Contá cómo recordás la primera pelea que resolvimos bien.",
        "Contá cómo recordás el día en que planeamos nuestro primer viaje juntos.",
        "Contá cómo recordás una charla nocturna que te marcó.",
        "Contá cómo recordás el momento en que sentiste más orgullo del otro.",
        "Contá cómo recordás la primera vez que nos reímos hasta llorar juntos.",
        "Contá cómo recordás un silencio cómodo que tuvimos alguna vez.",
        "Contá cómo recordás la primera vez que hablamos de nuestros miedos.",
        "Contá cómo recordás el día que uno de los dos tuvo un mal día y el otro lo sostuvo.",
        "Contá cómo recordás una charla sobre el futuro que te dio ilusión.",
        "Contá cómo recordás la primera canción que asociaste con nosotros.",
        "Contá cómo recordás el momento en que decidiste confiar del todo en el otro.",
        "Contá cómo recordás una foto o video que nos sacamos y por qué te gusta.",
        "Contá cómo recordás el día que nos dijimos algo difícil pero necesario.",
        "Contá cómo recordás la primera vez que sentiste celos, si pasó.",
        "Contá cómo recordás una charla filosófica o profunda que tuvimos.",
        "Contá cómo recordás la primera vez que hicimos un plan a largo plazo juntos.",
        "Contá cómo recordás la sensación de la última despedida antes de separarnos por la distancia.",
        "Contá cómo recordás el momento en que te diste cuenta de que me extrañabas de verdad.",
        "Contá cómo recordás una charla random que terminó siendo importante.",
        "Contá cómo recordás el día que hablamos de mudarnos juntos por primera vez.",
        "Contá cómo recordás una vez que te sorprendí (o me sorprendiste) sin avisar.",
        "Contá cómo recordás la primera vez que hablamos de nuestro pasado sentimental.",
        "Contá cómo recordás un momento incómodo que después se volvió gracioso.",
        "Contá cómo recordás la vez que uno de los dos casi cancela un plan importante.",
        "Contá cómo recordás la primera vez que nos enojamos por celos.",
        "Contá cómo recordás un consejo que me diste (o te di) que te cambió algo.",
        "Contá cómo recordás la primera vez que hablamos de tener hijos o no.",
        "Contá cómo recordás un momento de vulnerabilidad total del otro.",
        "Contá cómo recordás la primera vez que sentiste que 'esto es distinto a todo lo anterior'.",
        "Contá cómo recordás una charla sobre nuestros respectivos trabajos o estudios.",
        "Contá cómo recordás la primera vez que uno cuidó al otro estando enfermo, aunque sea a la distancia.",
        "Contá cómo recordás el día que hablamos de qué significa el amor para cada uno.",
        "Contá cómo recordás una charla sobre nuestras familias.",
        "Contá cómo recordás la primera vez que dijimos 'esto vale la pena' en voz alta.",
        "Contá cómo recordás una charla sobre nuestros defectos, sin pelear.",
        "Contá cómo recordás el día que decidiste que ibas a esperar, pase lo que pase.",
        "Contá cómo recordás una charla sobre celos o inseguridades que tuvimos.",
        "Contá cómo recordás la primera vez que uno defendió al otro frente a alguien más.",
        "Contá cómo recordás un chiste interno que nació de la nada.",
        "Contá cómo recordás la primera vez que hablamos en otro idioma entre nosotros, si pasó.",
        "Contá cómo recordás el día que uno de los dos dudó de la relación, si pasó.",
        "Contá cómo recordás la primera vez que planeamos algo para el futuro cercano juntos.",
        "Contá cómo recordás una charla sobre nuestros sueños personales, no en pareja.",
        "Contá cómo recordás la primera vez que nos mandamos una foto sin arreglar, tal cual estábamos.",
        "Contá cómo recordás la sensación de contarle a otra persona sobre nosotros por primera vez.",
        "Contá cómo recordás un día común, sin nada especial, que igual se sintió lindo.",
        "Contá cómo recordás la primera vez que hablamos de mudarnos de país.",
        "Contá cómo recordás una charla en la que uno cambió de opinión gracias al otro.",
        "Contá cómo recordás la primera vez que sentiste que podías ser 100% vos mismo/a conmigo.",
        "Contá cómo recordás una noche que no pudimos hablar por algún motivo, y cómo se sintió.",
        "Contá cómo recordás la vez que uno se disculpó primero sin que el otro lo pidiera.",
        "Contá cómo recordás la primera vez que hablamos de nuestras rutinas diarias.",
        "Contá cómo recordás una charla sobre qué esperamos del otro en una pelea.",
        "Contá cómo recordás la primera vez que hablamos de plata o finanzas entre nosotros.",
        "Contá cómo recordás el día que nos prometimos algo y lo cumplimos.",
        "Contá cómo recordás una charla sobre lo que más nos gusta del otro físicamente.",
        "Contá cómo recordás la primera vez que uno lloró frente al otro por videollamada.",
        "Contá cómo recordás la sensación de contar los días para el próximo reencuentro.",
        "Contá cómo recordás una charla sobre qué haríamos si algo saliera mal.",
        "Contá cómo recordás el momento en que sentiste alivio de haberte animado a esto.",
        "Contá cómo recordás una charla sobre nuestros gustos musicales distintos (o parecidos).",
        "Contá cómo recordás la primera vez que uno le puso un límite sano al otro.",
        "Contá cómo recordás el día que hablamos de qué haríamos si algún día dejáramos de sentir lo mismo.",
        "Contá cómo recordás una charla nocturna sobre el sentido de la vida.",
        "Contá cómo recordás la primera vez que uno le agradeció al otro por algo específico.",
        "Contá cómo recordás una charla sobre nuestros miedos a la soledad.",
        "Contá cómo recordás la primera vez que hicimos algo 'de pareja' aunque estuviéramos lejos (ver algo juntos, cocinar lo mismo, etc.).",
        "Contá cómo recordás el momento en que entendiste algo importante sobre cómo ama el otro.",
        "Contá cómo recordás una charla sobre qué haríamos distinto si volviéramos a empezar.",
        "Contá cómo recordás la primera vez que uno mencionó la palabra 'para siempre'.",
        "Contá cómo recordás un mensaje que releíste muchas veces.",
        "Contá cómo recordás la primera vez que uno mostró una parte vulnerable que nunca había mostrado.",
        "Contá cómo recordás una charla sobre qué significa 'hogar' para cada uno.",
        "Contá cómo recordás el momento en que decidiste priorizar esta relación por sobre otras cosas.",
        "Contá cómo recordás una charla sobre lo que aprendimos de relaciones pasadas.",
        "Contá cómo recordás la primera vez que uno dijo 'no sé qué haría sin vos'.",
        "Contá cómo recordás un plan que hicimos y todavía no cumplimos, pero seguimos sosteniendo.",
        "Contá cómo recordás la primera vez que sentiste que esta relación te hacía mejor persona.",
        "Contá cómo recordás una charla difícil sobre el futuro que terminó bien.",
        "Contá cómo recordás la sensación exacta de la primera vez que nos abrazamos."
    ]
};
