// ==================== NUNCAPREGUNTE (motor de reflexión) ====================
// Este juego usa js/motor-reflexion.js — acá sólo va su configuración.
// Banco expandido a 102 consignas.
window.CONFIG_REFLEXION = window.CONFIG_REFLEXION || {};
window.CONFIG_REFLEXION['nuncapregunte'] = {
    "tipo": "texto",
    "instrucciones": "Preguntas inesperadas para conversaciones profundas. Cada uno responde a solas.",
    "banco": [
        "¿Qué de tu infancia todavía te influye más de lo que te gustaría?",
        "¿Qué miedo tenés que casi nadie conoce?",
        "¿Qué deseo tenés que te da un poco de vergüenza admitir?",
        "¿Qué vínculo de tu vida marcó cómo amás hoy?",
        "¿Qué significa el amor para vos, más allá de lo que se dice?",
        "¿Qué parte de la intimidad valorás más: la física, la emocional o la mental?",
        "¿Cómo te imaginás en 10 años, sin pensar en nadie más?",
        "¿Qué parte de tu identidad sentís que todavía estás construyendo?",
        "¿Qué recuerdo de tu vida te gustaría poder contarme con lujo de detalle?",
        "¿Qué contradicción tenés que reconocés pero no resolvés?",
        "¿Qué te da más miedo: el compromiso o el abandono?",
        "¿Qué necesitabas de chico/a que no recibiste del todo?",
        "¿Qué es lo más difícil de confiar en alguien para vos?",
        "¿Qué versión tuya del pasado casi no reconocés hoy?",
        "¿Qué cosa nunca te preguntaron y te hubiese gustado que te pregunten?",
        "¿Qué es lo que más te costó perdonar en tu vida?",
        "¿Qué parte de vos cambia cuando estás enamorado/a?",
        "¿Qué creés de vos mismo/a que probablemente no es del todo cierto?",
        "¿Qué necesitás sentir para bajar la guardia con alguien?",
        "¿Qué le dirías a la persona que fuiste hace 5 años?",
        "¿Qué es algo que hacés por costumbre y nunca te preguntaste por qué?",
        "¿Qué es lo que más extrañás de una etapa pasada de tu vida?",
        "¿Qué es algo que aprendiste de una relación anterior que aplicás hoy?",
        "¿Qué es lo que más te gustaría cambiar de tu forma de amar?",
        "¿Qué situación te hace sentir más pequeño/a?",
        "¿Qué situación te hace sentir más poderoso/a?",
        "¿Qué es algo que dijiste una vez y te arrepentís?",
        "¿Qué es algo que no dijiste y te arrepentís?",
        "¿Qué parte de tu cuerpo te costó más aceptar?",
        "¿Qué es algo que creías a los 15 años que hoy te parece ridículo?",
        "¿Qué es algo que te enseñó el dolor que no te enseñó la alegría?",
        "¿Qué persona de tu vida te marcó sin que ella lo sepa?",
        "¿Qué es lo que más te asusta de envejecer?",
        "¿Qué es lo que más te ilusiona de envejecer?",
        "¿Qué es algo que necesitás escuchar más seguido, de cualquier persona?",
        "¿Qué parte de tu personalidad heredaste de alguien de tu familia, para bien o para mal?",
        "¿Qué es algo que perdonaste pero no olvidaste?",
        "¿Qué es algo que no perdonaste pero sí olvidaste, o intentás olvidar?",
        "¿Qué es lo más generoso que hiciste sin que nadie lo supiera?",
        "¿Qué es lo más egoísta que hiciste y todavía te pesa?",
        "¿Qué creencia tenías de chico/a sobre el amor que hoy cuestionás?",
        "¿Qué es algo que te gustaría que supieran de vos sin tener que explicarlo?",
        "¿Qué tan fácil o difícil te resulta pedir ayuda?",
        "¿Qué es algo que te da vergüenza que te guste?",
        "¿Qué es algo que odiás admitir que necesitás?",
        "¿Qué momento de soledad te marcó más en la vida?",
        "¿Qué persona te enseñó, sin querer, cómo NO querés que te traten?",
        "¿Qué es algo que te gustaría perdonarte a vos mismo/a?",
        "¿Qué tan cómodo/a te sentís mostrando tu enojo?",
        "¿Qué es algo que reprimís seguido sin darte cuenta?",
        "¿Qué tipo de amor viste crecer en tu familia, y qué tomaste de ahí?",
        "¿Qué es lo que más te cuesta de estar en pareja, en general?",
        "¿Qué es lo que más disfrutás de estar en pareja, en general?",
        "¿Qué es algo que te gustaría hacer sola/o antes de comprometerte más?",
        "¿Qué es algo de tu forma de ser que te costó aceptar en vos mismo/a?",
        "¿Qué es lo que más valorás cuando alguien te escucha?",
        "¿Qué situación reciente te hizo sentir muy vulnerable?",
        "¿Qué situación reciente te hizo sentir muy fuerte?",
        "¿Qué es algo que te gustaría dejar de necesitar validar en otros?",
        "¿Qué es lo que menos te gusta de pedir perdón?",
        "¿Qué es lo que más te gusta de perdonar a alguien?",
        "¿Qué tan seguido pensás en el futuro versus vivir el presente?",
        "¿Qué es algo que sacrificaste por amor y no te arrepentís?",
        "¿Qué es algo que sacrificaste por amor y sí te arrepentís?",
        "¿Qué te enseñó tu último gran fracaso?",
        "¿Qué te enseñó tu último gran logro?",
        "¿Qué parte de tu rutina diaria dice más de vos de lo que pensás?",
        "¿Qué es algo que te gustaría que la gente notara más en vos?",
        "¿Qué es algo que preferís que la gente no note en vos?",
        "¿Qué tan fácil te resulta confiar en el amor después de una decepción?",
        "¿Qué es algo que aprendiste sobre vos mismo/a en esta relación a distancia?",
        "¿Qué es lo que más te asusta de que esto se vuelva algo cotidiano?",
        "¿Qué es lo que más te ilusiona de que esto se vuelva algo cotidiano?",
        "¿Qué palabra usarías para describir cómo amás?",
        "¿Qué palabra usarías para describir cómo te gustaría que te amen?",
        "¿Qué es algo que necesitás de un vínculo para sentirte en paz?",
        "¿Qué es lo que más te cuesta soltar del pasado?",
        "¿Qué es lo primero que notás en una persona cuando la conocés?",
        "¿Qué es lo último que se te olvida de alguien que ya no está en tu vida?",
        "¿Qué relación (no romántica) marcó tu forma de vincularte con los demás?",
        "¿Qué es algo que hoy te resulta fácil y antes te costaba mucho?",
        "¿Qué es algo que antes te resultaba fácil y hoy te cuesta más?",
        "¿Qué es lo que más admirás de las personas que amás?",
        "¿Qué es algo que te gustaría que tus futuros hijos (si los tenés) sepan de vos?",
        "¿Qué es algo de tu forma de discutir que te gustaría cambiar?",
        "¿Qué es algo de tu forma de discutir de lo que estás orgulloso/a?",
        "¿Qué tanto te cuesta estar solo/a con tus pensamientos?",
        "¿Qué es algo que aprendiste tarde en la vida y te hubiese gustado saber antes?",
        "¿Qué recuerdo de tu adolescencia todavía te da vergüenza?",
        "¿Qué recuerdo de tu adolescencia todavía te da orgullo?",
        "¿Qué es lo que más te costó decirme en esta relación?",
        "¿Qué es algo que todavía no me dijiste porque no encontrás el momento?",
        "¿Qué tan importante es para vos que te digan 'te amo' seguido?",
        "¿Qué gesto pequeño te hace sentir más amado/a que mil palabras?",
        "¿Qué es lo que más te costó de crecer en la familia que te tocó?",
        "¿Qué es lo que más agradecés de la familia que te tocó?",
        "¿Qué es algo que te gustaría reparar con alguien de tu pasado?",
        "¿Qué es algo que ya reparaste con alguien de tu pasado?",
        "¿Qué tan seguido sentís que merecés lo bueno que te pasa?",
        "¿Qué es algo que te cuesta creer sobre vos mismo/a, aunque otros te lo digan?",
        "¿Qué es algo que te gustaría que yo entendiera sin tener que explicarlo cada vez?",
        "¿Qué es algo que descubriste sobre el amor gracias a esta distancia?"
    ]
};
