// ==================== QUEHARIASSI (motor de reflexión) ====================
// Este juego usa js/motor-reflexion.js — acá sólo va su configuración.
// Banco expandido a 100 consignas.
window.CONFIG_REFLEXION = window.CONFIG_REFLEXION || {};
window.CONFIG_REFLEXION['quehariassi'] = {
    "tipo": "texto",
    "instrucciones": "Situaciones absurdas, románticas y filosóficas. Respondan sin verse hasta que ambos terminen.",
    "placeholder": "Qué harías si...",
    "banco": [
        "Nos despertamos mañana y tenemos un millón de dólares. ¿Qué hacés primero?",
        "Sólo podemos comer una comida durante un año. ¿Cuál elegís y por qué?",
        "Tenemos que vivir un mes en otro país, sin elegir cuál. ¿Cómo te imaginás?",
        "Intercambiamos cuerpos durante 24 horas. ¿Qué es lo primero que hacés en el mío?",
        "Podemos borrar un solo recuerdo de nuestra historia. ¿Lo harías? ¿Cuál?",
        "Un extraterrestre nos invita a viajar con él, sin garantía de volver. ¿Vas?",
        "Tenemos que comunicarnos sólo con memes durante una semana. ¿Cómo te va?",
        "Ganamos un viaje a cualquier lugar del mundo, pero sale mañana. ¿A dónde?",
        "Nos ofrecen saber el día exacto en que vamos a morir. ¿Querés saberlo?",
        "Podemos pausar el tiempo por un día entero, solo para nosotros. ¿Qué hacemos?",
        "Tenemos que elegir un superpoder para toda la vida. ¿Cuál y por qué?",
        "Nos regalan una casa, pero en el lugar más random del mundo. ¿La aceptás?",
        "Un genio te concede un deseo, pero sólo si es para los dos. ¿Qué pedís?",
        "Nos quedamos sin batería de celular por una semana entera. ¿Cómo seguimos?",
        "Podemos revivir un solo día de nuestra historia juntos. ¿Cuál elegís?",
        "Nos ofrecen fama mundial a cambio de nunca más vernos en persona. ¿Aceptás?",
        "Tenemos que mudarnos juntos mañana mismo, sin planear nada. ¿Cómo reaccionás?",
        "Podés cambiar una decisión del pasado sin consecuencias. ¿Cuál cambiarías?",
        "Nos regalan una máquina del tiempo, un solo viaje. ¿A qué momento nuestro volverías?",
        "Si hoy fuera el último día para decirme algo, ¿qué me dirías?",
        "Nos despertamos y ya no existe la distancia entre nosotros. ¿Qué hacés en la primera hora?",
        "Tenemos que elegir entre no volver a discutir nunca o no volver a reírnos juntos. ¿Qué elegís?",
        "Un hada te da la posibilidad de saber qué piensa el otro por un día. ¿La usarías?",
        "Si mañana perdiéramos todo lo material pero nos tuviéramos a nosotros, ¿cómo seguirías?",
        "Podemos elegir vivir en cualquier época de la historia, juntos. ¿Cuál elegirías?",
        "Si tuvieras que convencerme de algo importante en 30 segundos, ¿qué me dirías?",
        "Nos ofrecen la posibilidad de saber si en 5 años seguimos juntos. ¿Preguntarías?",
        "Si sólo pudieras salvar una foto nuestra de un incendio, ¿cuál sería?",
        "Tenemos que dar una charla TED sobre nuestra relación mañana. ¿De qué hablarías?",
        "Si pudieras vivir un año entero sin trabajar, ¿qué harías conmigo ese año?",
        "Nos dan la opción de vivir para siempre jóvenes pero sin poder tener hijos. ¿La tomás?",
        "Si tu yo del futuro te mandara un mensaje hoy, ¿qué creés que diría sobre nosotros?",
        "Tenemos que elegir un país para nunca más poder visitar. ¿Cuál sacrificás?",
        "Si pudieras hacerme una sola pregunta y yo tuviera que responder 100% honesto, ¿cuál sería?",
        "Nos regalan boletos para el primer vuelo comercial a la Luna. ¿Vamos?",
        "Si tuvieras que resumir nuestra relación en una película, ¿qué género sería y por qué?",
        "Podés elegir un talento nuevo para mí. ¿Cuál me darías?",
        "Si esta fuera la última semana de la distancia antes de vivir juntos para siempre, ¿qué harías distinto?",
        "Nos dan a elegir entre vivir 100 años separados o 20 años juntos. ¿Qué elegís?",
        "Si pudieras escuchar el pensamiento que tuve hoy sobre vos, ¿te gustaría saberlo ahora?",
        "Tenemos que dejar todo y mudarnos a un barco por un año. ¿Cómo te la imaginás?",
        "Si pudieras vivir dentro de un recuerdo nuestro por un día, ¿cuál elegirías?",
        "Nos ofrecen la chance de conocer a nuestros hijos del futuro por 10 minutos. ¿Querés?",
        "Si tuvieras que enseñarme algo de tu cultura en un día, ¿qué elegirías?",
        "Tenemos que elegir entre perder el sentido del humor o la memoria de corto plazo. ¿Qué eligís?",
        "Si pudieras hacer que dejemos de pelear por un tema específico para siempre, ¿cuál sería?",
        "Nos regalan la casa de nuestros sueños pero en un lugar sin internet. ¿La aceptás?",
        "Si mañana tuviéramos que decidir en qué ciudad vivir para siempre, ¿cuál proponés?",
        "Tenemos que elegir un objeto que represente nuestra relación para meter en una cápsula del tiempo. ¿Cuál?",
        "Si pudieras vivir sin dormir pero sin cansarte, ¿qué harías con esas horas extra conmigo?",
        "Nos dan la chance de reescribir el día en que nos conocimos. ¿Cambiarías algo?",
        "Si tuvieras que elegir entre perder todos tus recuerdos de otras personas o de mí, ¿qué elegirías conservar?",
        "Tenemos que sobrevivir un mes con lo que hay en la heladera de cada uno. ¿Cómo nos va?",
        "Si pudieras teletransportarte a mi lado ahora mismo por sólo una hora, ¿qué haríamos?",
        "Nos ofrecen viajar en el tiempo hasta el día en que naciste. ¿Irías a verte de bebé?",
        "Si tuvieras que dejar un mensaje de voz para que lo escuche dentro de 10 años, ¿qué dirías?",
        "Tenemos que elegir un superpoder colectivo para la pareja. ¿Cuál sería el más útil para nosotros?",
        "Si pudieras vivir en cualquier libro o película con nosotros como protagonistas, ¿cuál elegirías?",
        "Nos regalan un año sabático para hacer lo que queramos. ¿Qué harías vos?",
        "Si tuvieras que elegir entre tener razón siempre o ser feliz siempre, ¿qué elegís?",
        "Tenemos que decidir juntos si mudarnos a la ciudad o al campo para siempre. ¿Qué elegís?",
        "Si pudieras ver un solo día de mi futuro sin mí en él, ¿lo mirarías?",
        "Nos ofrecen borrar la palabra 'no' de nuestro vocabulario por una semana. ¿Aceptás?",
        "Si tuvieras que dar un discurso en nuestra boda (real o imaginaria), ¿qué dirías?",
        "Tenemos que elegir vivir un mes sin ningún tipo de tecnología. ¿Cómo te la imaginás?",
        "Si pudieras cambiar el clima de donde vivo para que se parezca más al tuyo, ¿lo harías?",
        "Nos regalan la posibilidad de aprender el idioma del otro perfectamente en un día. ¿Lo usarías?",
        "Si tuvieras que elegir un animal que nos represente como pareja, ¿cuál sería?",
        "Tenemos que armar un plan de escape si el mundo se termina mañana. ¿Cuál sería?",
        "Si pudieras saber qué pensaba de vos la primera vez que me viste (sin preguntarme), ¿te gustaría?",
        "Nos ofrecen vivir literalmente dentro de nuestras fotos favoritas por un rato. ¿Cuál elegís?",
        "Si tuvieras que elegir entre perder la vista o el oído, sabiendo que seguiríamos juntos, ¿qué elegís?",
        "Tenemos que preparar una cápsula del tiempo para abrir en 20 años. ¿Qué meterías?",
        "Si pudieras cambiar un hábito mío con un chasquido de dedos, ¿lo harías?",
        "Nos dan a elegir entre un mes de vacaciones ilimitadas o un aumento enorme de sueldo. ¿Qué elegís?",
        "Si tuvieras que mudarte de continente mañana sin avisar a nadie, ¿lo harías por mí?",
        "Tenemos que sobrevivir un fin de semana sin hablar, sólo con gestos. ¿Cómo nos va?",
        "Si pudieras vivir literalmente adentro de una canción que nos representa, ¿cuál elegirías?",
        "Nos regalan la chance de conocer a nuestras versiones de hace 10 años. ¿Qué les dirías?",
        "Si tuvieras que elegir un lugar del mundo para pedirme matrimonio (hipotéticamente), ¿cuál sería?",
        "Tenemos que decidir entre vivir sin dinero pero felices, o con mucho dinero pero estresados. ¿Qué elegís?",
        "Si pudieras escuchar la voz de nuestro 'nosotros' del futuro dándonos un consejo, ¿qué creés que diría?",
        "Nos ofrecen la posibilidad de repetir nuestra primera cita exactamente igual. ¿La repetirías?",
        "Si tuvieras que elegir el soundtrack de nuestra vida juntos, ¿qué tres canciones no podrían faltar?",
        "Tenemos que decidir si mudarnos apenas podamos o esperar el momento 'perfecto'. ¿Qué elegís?",
        "Si pudieras ver el final de nuestra historia ahora mismo, ¿querrías saberlo?",
        "Nos regalan la chance de vivir un día entero como el otro, viendo el mundo con sus ojos. ¿Lo harías?",
        "Si tuvieras que elegir una sola virtud tuya para dejarme como herencia, ¿cuál sería?",
        "Tenemos que planear el reencuentro perfecto sin límite de presupuesto. ¿Cómo sería?",
        "Si pudieras vivir sabiendo que cada 'te amo' es literal y con peso real, ¿lo dirías más seguido?",
        "Nos ofrecen intercambiar un miedo tuyo por uno mío. ¿Lo harías?",
        "Si tuvieras que elegir el lugar exacto donde vivir juntos para siempre, ahora mismo, ¿cuál sería?",
        "Tenemos que decidir si mudarnos cerca de tu familia o de la mía. ¿Qué proponés?",
        "Si pudieras congelar un momento nuestro para vivir en loop por una semana, ¿cuál elegirías?",
        "Nos regalan la posibilidad de saber la verdad absoluta sobre cualquier duda que tengas de mí. ¿La usarías?",
        "Si tuvieras que resumir en una palabra lo que sentís ahora mismo por nosotros, ¿cuál sería?",
        "Tenemos que decidir entre tener una vida tranquila y predecible, o una llena de sorpresas y riesgo. ¿Qué elegís?",
        "Si pudieras hacer que un miedo mío desaparezca para siempre, ¿cuál elegirías borrar?",
        "Nos ofrecen vivir 100 vidas distintas, pero sólo si en cada una nos volvemos a encontrar. ¿Aceptás?",
        "Si tuvieras que elegir el nombre de nuestra futura mascota o hijo/a ahora mismo, ¿cuál sería?"
    ]
};
