// ==================== TRIVIA DE NOSOTROS (motor de reflexión) ====================
// 104 preguntas. La lista muestra el marcador de coincidencias (motor).
window.CONFIG_REFLEXION = window.CONFIG_REFLEXION || {};
window.CONFIG_REFLEXION['trivianosotros'] = {
    tipo: 'opciones',
    desempatePorSorteo: false,
    instrucciones: 'Preguntas sobre gustos y costumbres de cada uno. Elijan qué creen que es cierto — si coinciden con la realidad, mejor todavía.',
    banco: [
        { texto: '¿Cuál de los dos tarda más en quedarse dormido?', opciones: ['Nico', 'Carito', 'Los dos igual'] },
        { texto: '¿Quién es más de madrugar?', opciones: ['Nico', 'Carito', 'Ninguno de los dos'] },
        { texto: '¿A quién le gusta más el picante?', opciones: ['Nico', 'Carito', 'A los dos por igual'] },
        { texto: '¿Quién es más ordenado/a con sus cosas?', opciones: ['Nico', 'Carito', 'Ninguno, la verdad'] },
        { texto: '¿Quién llora más fácil con una película?', opciones: ['Nico', 'Carito', 'Ninguno'] },
        { texto: '¿A quién le cuesta más pedir perdón primero?', opciones: ['Nico', 'Carito', 'A los dos por igual'] },
        { texto: '¿Quién es más de planificar todo con anticipación?', opciones: ['Nico', 'Carito', 'Ninguno, improvisan'] },
        { texto: '¿A quién le gusta más el silencio?', opciones: ['Nico', 'Carito', 'A los dos'] },
        { texto: '¿Quién es más gastador/a?', opciones: ['Nico', 'Carito', 'Ahorran parecido'] },
        { texto: '¿Quién tiene mejor sentido de la orientación?', opciones: ['Nico', 'Carito', 'Ninguno'] },
        { texto: '¿A quién le da más vergüenza cantar en público?', opciones: ['Nico', 'Carito', 'A ninguno'] },
        { texto: '¿Quién es más celoso/a?', opciones: ['Nico', 'Carito', 'Ninguno de los dos'] },
        { texto: '¿A quién le gusta más el chocolate?', opciones: ['Nico', 'Carito', 'A los dos igual'] },
        { texto: '¿Quién tarda más en arreglarse para salir?', opciones: ['Nico', 'Carito', 'Tardan igual'] },
        { texto: '¿A quién le cuesta más admitir que se equivocó?', opciones: ['Nico', 'Carito', 'A ninguno'] },
        { texto: '¿Quién es más de escuchar música fuerte?', opciones: ['Nico', 'Carito', 'A los dos'] },
        { texto: '¿A quién le gusta más dormir la siesta?', opciones: ['Nico', 'Carito', 'A los dos'] },
        { texto: '¿Quién es más impulsivo/a al comprar algo?', opciones: ['Nico', 'Carito', 'Ninguno'] },
        { texto: '¿A quién le cuesta más el inglés (u otro idioma)?', opciones: ['Nico', 'Carito', 'A ninguno'] },
        { texto: '¿Quién se enoja más rápido?', opciones: ['Nico', 'Carito', 'A los dos les cuesta igual'] },
        { texto: '¿A quién le gusta más cocinar?', opciones: ['Nico', 'Carito', 'A los dos'] },
        { texto: '¿Quién tiene el humor más ácido?', opciones: ['Nico', 'Carito', 'Parecido'] },
        { texto: '¿A quién le gustan más los animales?', opciones: ['Nico', 'Carito', 'A los dos por igual'] },
        { texto: '¿Quién es más fan de las redes sociales?', opciones: ['Nico', 'Carito', 'A ninguno le importan mucho'] },
        { texto: '¿A quién le gusta más viajar sin planear nada?', opciones: ['Nico', 'Carito', 'A los dos'] },
        { texto: '¿Quién se acuerda mejor de las fechas importantes?', opciones: ['Nico', 'Carito', 'Ninguno, la verdad'] },
        { texto: '¿A quién le gusta más el frío?', opciones: ['Nico', 'Carito', 'A ninguno'] },
        { texto: '¿Quién es más terco/a en una discusión?', opciones: ['Nico', 'Carito', 'Los dos por igual'] },
        { texto: '¿A quién le da más miedo el terror en el cine?', opciones: ['Nico', 'Carito', 'A ninguno'] },
        { texto: '¿Quién es más fan del café?', opciones: ['Nico', 'Carito', 'A los dos'] },
        { texto: '¿Quién canta peor (pero con más ganas)?', opciones: ['Nico', 'Carito', 'Los dos igual de desafinados'] },
        { texto: '¿Quién es más de mandar stickers?', opciones: ['Nico', 'Carito', 'Los dos por igual'] },
        { texto: '¿Quién pide perdón con un regalito?', opciones: ['Nico', 'Carito', 'Ninguno, se pide con palabras'] },
        { texto: '¿Quién tiene más paciencia?', opciones: ['Nico', 'Carito', 'Parecido'] },
        { texto: '¿Quién se ríe más fuerte?', opciones: ['Nico', 'Carito', 'Los dos igual'] },
        { texto: '¿A quién le gusta más el mate?', opciones: ['Nico', 'Carito', 'A los dos por igual'] },
        { texto: '¿Quién es más de quedarse en casa un sábado?', opciones: ['Nico', 'Carito', 'A los dos'] },
        { texto: '¿Quién se pierde más en un shopping?', opciones: ['Nico', 'Carito', 'Ninguno'] },
        { texto: '¿Quién es más fotogénico/a?', opciones: ['Nico', 'Carito', 'Los dos'] },
        { texto: '¿Quién es más de recordar los nombres de la gente?', opciones: ['Nico', 'Carito', 'Ninguno, la verdad'] },
        { texto: '¿Quién tiene más ropa que no usa?', opciones: ['Nico', 'Carito', 'Parecido'] },
        { texto: '¿Quién se pone más nervioso/a antes de un evento importante?', opciones: ['Nico', 'Carito', 'Los dos igual'] },
        { texto: '¿Quién es más de hacer regalos sorpresa?', opciones: ['Nico', 'Carito', 'Los dos'] },
        { texto: '¿Quién es más competitivo/a en los juegos?', opciones: ['Nico', 'Carito', 'Los dos por igual'] },
        { texto: '¿Quién es más dormilón/a?', opciones: ['Nico', 'Carito', 'Los dos'] },
        { texto: "¿Quién es más de decir 'te amo' primero?", opciones: ['Nico', 'Carito', 'Los dos por igual'] },
        { texto: '¿Quién tiene la letra más linda?', opciones: ['Nico', 'Carito', 'Parecido'] },
        { texto: '¿A quién le gusta más bailar?', opciones: ['Nico', 'Carito', 'A los dos'] },
        { texto: '¿Quién cocina mejor?', opciones: ['Nico', 'Carito', 'Empate técnico'] },
        { texto: '¿Quién es más de llorar de risa?', opciones: ['Nico', 'Carito', 'Los dos'] },
        { texto: '¿Quién tarda más en elegir qué comer en un restaurante?', opciones: ['Nico', 'Carito', 'Tardan igual'] },
        { texto: '¿Quién es más de tener la última palabra?', opciones: ['Nico', 'Carito', 'Ninguno'] },
        { texto: '¿Quién se acuerda más de los sueños?', opciones: ['Nico', 'Carito', 'Ninguno'] },
        { texto: '¿Quién es más sensible con las películas de animales?', opciones: ['Nico', 'Carito', 'Los dos'] },
        { texto: '¿Quién es más de escribir mensajes largos?', opciones: ['Nico', 'Carito', 'Parecido'] },
        { texto: '¿Quién es más fan de las series?', opciones: ['Nico', 'Carito', 'A los dos por igual'] },
        { texto: '¿Quién deja más cosas para último momento?', opciones: ['Nico', 'Carito', 'Los dos por igual'] },
        { texto: '¿A quién le gusta más la playa?', opciones: ['Nico', 'Carito', 'A los dos'] },
        { texto: '¿A quién le gusta más la montaña?', opciones: ['Nico', 'Carito', 'A los dos'] },
        { texto: '¿Quién es más de hacer listas?', opciones: ['Nico', 'Carito', 'Ninguno'] },
        { texto: '¿Quién es más friolento/a?', opciones: ['Nico', 'Carito', 'Los dos'] },
        { texto: '¿Quién es más de comer dulce?', opciones: ['Nico', 'Carito', 'A los dos'] },
        { texto: '¿Quién es más de comer salado?', opciones: ['Nico', 'Carito', 'A los dos'] },
        { texto: '¿Quién es más de cantar en el auto?', opciones: ['Nico', 'Carito', 'Los dos'] },
        { texto: '¿Quién es más curioso/a?', opciones: ['Nico', 'Carito', 'Parecido'] },
        { texto: '¿Quién es más de dar consejos?', opciones: ['Nico', 'Carito', 'Los dos por igual'] },
        { texto: '¿Quién tiene más amigos?', opciones: ['Nico', 'Carito', 'Parecido'] },
        { texto: '¿Quién es más de improvisar un plan?', opciones: ['Nico', 'Carito', 'Los dos'] },
        { texto: '¿Quién es mejor perdiendo en un juego?', opciones: ['Nico', 'Carito', 'Ninguno, los dos son malos perdedores'] },
        { texto: '¿Quién es más de despertarse con alarma doble?', opciones: ['Nico', 'Carito', 'Los dos'] },
        { texto: '¿Quién usa más emojis?', opciones: ['Nico', 'Carito', 'Los dos por igual'] },
        { texto: '¿Quién es más de hablar dormido/a?', opciones: ['Nico', 'Carito', 'Ninguno'] },
        { texto: '¿A quién le cuesta más decir que no?', opciones: ['Nico', 'Carito', 'A los dos'] },
        { texto: '¿Quién tiene más miedo a los bichos?', opciones: ['Nico', 'Carito', 'A ninguno'] },
        { texto: '¿Quién es más de buscar la mejor oferta antes de comprar?', opciones: ['Nico', 'Carito', 'Parecido'] },
        { texto: '¿Quién es más de cuidar las plantas?', opciones: ['Nico', 'Carito', 'Los dos'] },
        { texto: '¿Quién es más de contar chistes malos?', opciones: ['Nico', 'Carito', 'Los dos por igual'] },
        { texto: '¿Quién se emociona más en los cumpleaños?', opciones: ['Nico', 'Carito', 'Los dos'] },
        { texto: '¿Quién es más de proponer una salida?', opciones: ['Nico', 'Carito', 'Parecido'] },
        { texto: '¿Quién es más de dormirse mirando una película?', opciones: ['Nico', 'Carito', 'Los dos'] },
        { texto: '¿Quién es más de tener razón (según sí mismo/a)?', opciones: ['Nico', 'Carito', 'Los dos por igual'] },
        { texto: '¿Quién tiene más paciencia con la tecnología?', opciones: ['Nico', 'Carito', 'Ninguno'] },
        { texto: '¿Quién es más de sacar fotos de la comida?', opciones: ['Nico', 'Carito', 'A ninguno'] },
        { texto: '¿Quién es más romántico/a?', opciones: ['Nico', 'Carito', 'Los dos'] },
        { texto: '¿Quién es más de guardar recuerdos (entradas, tickets, cartas)?', opciones: ['Nico', 'Carito', 'Los dos'] },
        { texto: '¿Quién se adapta más rápido a los cambios?', opciones: ['Nico', 'Carito', 'Parecido'] },
        { texto: '¿Quién es más de ordenar la casa cuando está estresado/a?', opciones: ['Nico', 'Carito', 'Ninguno'] },
        { texto: '¿Quién es más de saludar a los perros por la calle?', opciones: ['Nico', 'Carito', 'Los dos'] },
        { texto: '¿Quién es más de pedir comida por delivery?', opciones: ['Nico', 'Carito', 'Los dos por igual'] },
        { texto: '¿Quién es más de quedarse charlando hasta tarde?', opciones: ['Nico', 'Carito', 'Los dos'] },
        { texto: '¿Quién es más de hacer planes a futuro?', opciones: ['Nico', 'Carito', 'Parecido'] },
        { texto: '¿Quién es más puntual?', opciones: ['Nico', 'Carito', 'Ninguno, la verdad'] },
        { texto: '¿Quién se pone más mimoso/a cuando está cansado/a?', opciones: ['Nico', 'Carito', 'Los dos'] },
        { texto: '¿Quién es más de reírse de sí mismo/a?', opciones: ['Nico', 'Carito', 'Los dos'] },
        { texto: '¿Quién es más de probar comidas nuevas?', opciones: ['Nico', 'Carito', 'A los dos'] },
        { texto: '¿Quién es más de tener un plan B?', opciones: ['Nico', 'Carito', 'Ninguno'] },
        { texto: '¿Quién es más de enojarse con el tránsito?', opciones: ['Nico', 'Carito', 'Los dos por igual'] },
        { texto: '¿Quién es más de mirar el celular antes de dormir?', opciones: ['Nico', 'Carito', 'Los dos'] },
        { texto: '¿Quién es más de escuchar la misma canción en loop?', opciones: ['Nico', 'Carito', 'Los dos'] },
        { texto: '¿Quién se acuerda mejor de nuestra primera cita?', opciones: ['Nico', 'Carito', 'Los dos igual'] },
        { texto: "¿Quién dijo 'te quiero' primero?", opciones: ['Nico', 'Carito', 'No nos acordamos'] },
        { texto: '¿Quién es más de festejar los aniversarios?', opciones: ['Nico', 'Carito', 'Los dos'] },
        { texto: '¿Quién es más de perdonar rápido?', opciones: ['Nico', 'Carito', 'Los dos por igual'] },
        { texto: '¿Quién es más de cuidar al otro cuando está enfermo?', opciones: ['Nico', 'Carito', 'Los dos por igual'] },
    ]
};
