// ==================== TRIVIA DE NOSOTROS (motor de reflexión) ====================
window.CONFIG_REFLEXION = window.CONFIG_REFLEXION || {};
window.CONFIG_REFLEXION['trivianosotros'] = {
    tipo: 'opciones',
    desempatePorSorteo: false,
    instrucciones: 'Preguntas sobre gustos y costumbres de cada uno. Elijan qué creen que es cierto — si coinciden con la realidad, mejor todavía.',
    banco: [
        { texto: '¿Cuál de los dos tarda más en quedarse dormido?', opciones: ['Nico', 'Carito', 'Los dos igual'] },
        { texto: '¿Quién es más de madrugar?', opciones: ['Nico', 'Carito', 'Ninguno de los dos'] },
        { texto: '¿A quién le gusta más el picante?', opciones: ['Nico', 'Carito', 'A los dos por igual'] },
        { texto: '¿Quién es más ordenado/a con sus cosas?', opciones: ['Nico', 'Carito', 'Ninguno, la verdad'] },
        { texto: '¿Quién llora más fácil con una película?', opciones: ['Nico', 'Carito', 'Ninguno'] },
        { texto: '¿A quién le cuesta más pedir perdón primero?', opciones: ['Nico', 'Carito', 'A los dos por igual'] },
        { texto: '¿Quién es más de planificar todo con anticipación?', opciones: ['Nico', 'Carito', 'Ninguno, improvisan'] },
        { texto: '¿A quién le gusta más el silencio?', opciones: ['Nico', 'Carito', 'A los dos'] },
        { texto: '¿Quién es más gastador/a?', opciones: ['Nico', 'Carito', 'Ahorran parecido'] },
        { texto: '¿Quién tiene mejor sentido de la orientación?', opciones: ['Nico', 'Carito', 'Ninguno'] },
        { texto: '¿A quién le da más vergüenza cantar en público?', opciones: ['Nico', 'Carito', 'A ninguno'] },
        { texto: '¿Quién es más celoso/a?', opciones: ['Nico', 'Carito', 'Ninguno de los dos'] },
        { texto: '¿A quién le gusta más el chocolate?', opciones: ['Nico', 'Carito', 'A los dos igual'] },
        { texto: '¿Quién tarda más en arreglarse para salir?', opciones: ['Nico', 'Carito', 'Tardan igual'] },
        { texto: '¿A quién le cuesta más admitir que se equivocó?', opciones: ['Nico', 'Carito', 'A ninguno'] },
        { texto: '¿Quién es más de escuchar música fuerte?', opciones: ['Nico', 'Carito', 'A los dos'] },
        { texto: '¿A quién le gusta más dormir la siesta?', opciones: ['Nico', 'Carito', 'A los dos'] },
        { texto: '¿Quién es más impulsivo/a al comprar algo?', opciones: ['Nico', 'Carito', 'Ninguno'] },
        { texto: '¿A quién le cuesta más el inglés (u otro idioma)?', opciones: ['Nico', 'Carito', 'A ninguno'] },
        { texto: '¿Quién se enoja más rápido?', opciones: ['Nico', 'Carito', 'A los dos les cuesta igual'] },
        { texto: '¿A quién le gusta más cocinar?', opciones: ['Nico', 'Carito', 'A los dos'] },
        { texto: '¿Quién tiene el humor más ácido?', opciones: ['Nico', 'Carito', 'Parecido'] },
        { texto: '¿A quién le gustan más los animales?', opciones: ['Nico', 'Carito', 'A los dos por igual'] },
        { texto: '¿Quién es más fan de las redes sociales?', opciones: ['Nico', 'Carito', 'A ninguno le importan mucho'] },
        { texto: '¿A quién le gusta más viajar sin planear nada?', opciones: ['Nico', 'Carito', 'A los dos'] },
        { texto: '¿Quién se acuerda mejor de las fechas importantes?', opciones: ['Nico', 'Carito', 'Ninguno, la verdad'] },
        { texto: '¿A quién le gusta más el frío?', opciones: ['Nico', 'Carito', 'A ninguno'] },
        { texto: '¿Quién es más terco/a en una discusión?', opciones: ['Nico', 'Carito', 'Los dos por igual'] },
        { texto: '¿A quién le da más miedo el terror en el cine?', opciones: ['Nico', 'Carito', 'A ninguno'] },
        { texto: '¿Quién es más fan del café?', opciones: ['Nico', 'Carito', 'A los dos'] },
    ]
};
