// ==================== PING PONG DE PREGUNTAS (motor de reflexión) ====================
// Banco ampliado: además de las 284 preguntas originales del índice, suma
// las consignas de texto libre de quehariassi, futuro, maquinatiempo,
// album y nuncapregunte (cada juego conserva su propio banco intacto;
// acá sólo se copiaron los textos). Total: 787 preguntas.
// Los dos pueden responderla acá mismo, revelan juntos, y además pueden
// seguir mandándola por WhatsApp si quieren.
window.CONFIG_REFLEXION = window.CONFIG_REFLEXION || {};
window.CONFIG_REFLEXION['preguntasindex'] = {
    tipo: 'texto',
    placeholder: 'Tu respuesta...',
    instrucciones: 'Una pregunta para los dos. Respondan por su lado y revelen juntos.',
    compartirWhatsApp: true,
    numerosWhatsApp: { nico: '5493516575261', carito: '5491170131229' },
    banco: [
    "¿Cuál fue el primer momento en que sentiste que esta relación era diferente a las demás?",
    "¿Qué recuerdo nuestro te hace sonreír instantáneamente?",
    "¿Qué conversación nuestra nunca quisieras olvidar?",
    "¿Qué detalle mío te sorprendió al principio?",
    "¿Cuál fue el día más emocionante que vivimos juntos?",
    "¿Qué recuerdo te gustaría volver a vivir exactamente igual?",
    "¿Qué momento marcó un antes y un después para nosotros?",
    "¿Qué foto nuestra cuenta mejor nuestra historia?",
    "¿Cuál fue tu primera impresión de mí y cuánto cambió?",
    "¿Qué mensaje mío recuerdas con más cariño?",
    "¿Qué momento te hizo sentir especialmente amado/a?",
    "¿Qué pequeña anécdota merece estar en un libro sobre nosotros?",
    "¿Cuál fue nuestro momento más espontáneo?",
    "¿Qué recuerdo te genera más ternura?",
    "¿Qué recuerdo te gustaría contarles algún día a nuestros nietos?",
    "¿Cuál fue nuestra etapa más divertida?",
    "¿Qué situación difícil nos hizo más fuertes?",
    "¿Qué regalo o detalle significó más para ti?",
    "¿Qué recuerdo te hace pensar 'qué suerte tuve'?",
    "¿Cuál fue nuestra primera gran aventura?",
    "¿Qué momento cotidiano terminó convirtiéndose en algo especial?",
    "¿Qué recuerdo sigue emocionándote como el primer día?",
    "¿Qué escena de nuestra historia parece sacada de una película?",
    "¿Qué recuerdo te gustaría conservar para siempre en una cápsula del tiempo?",
    "¿Cuál fue la primera vez que te sentiste realmente comprendido/a por mí?",
    "¿Qué recuerdo te hace reír más fuerte?",
    "¿Qué costumbre nació por casualidad y se volvió importante?",
    "¿Cuál fue el mejor reencuentro que hemos tenido?",
    "¿Qué recuerdo te hace sentir más orgulloso/a de nosotros?",
    "¿Qué momento te hizo pensar que éramos un gran equipo?",
    "¿Qué recuerdo te hace extrañarme más?",
    "¿Qué viaje o salida recuerdas con más cariño?",
    "¿Qué detalle mío descubriste con el tiempo?",
    "¿Qué momento te hizo enamorarte un poco más?",
    "¿Qué recuerdo tiene una canción especial asociada?",
    "¿Cuál fue nuestro momento más romántico?",
    "¿Qué recuerdo te gustaría revivir durante un día entero?",
    "¿Qué experiencia nos unió más?",
    "¿Qué recuerdo demuestra cuánto hemos crecido juntos?",
    "¿Qué rutina nuestra extrañarías más?",
    "¿Cuál es nuestro chiste interno favorito?",
    "¿Qué hago sin darme cuenta que te hace feliz?",
    "¿Cuál es nuestro ritual más especial?",
    "¿Qué costumbre compartida te da tranquilidad?",
    "¿Qué momento del día asocias más conmigo?",
    "¿Qué palabra o frase nuestra tiene un significado especial?",
    "¿Qué hábito mío te resulta adorable?",
    "¿Qué costumbre nuestra nunca deberíamos perder?",
    "¿Qué hacemos juntos que parece insignificante pero significa mucho?",
    "¿Cuál es nuestra tradición más linda?",
    "¿Qué gesto cotidiano te hace sentir amado/a?",
    "¿Qué actividad compartida nos representa mejor?",
    "¿Qué pequeña locura hacemos que nadie entendería?",
    "¿Qué es lo primero que te gustaría contarme cuando te pasa algo bueno?",
    "¿Qué es lo primero que te gustaría contarme cuando te pasa algo malo?",
    "¿Qué momento simple se volvió imprescindible?",
    "¿Cuál es nuestro idioma secreto?",
    "¿Qué costumbre nació accidentalmente?",
    "¿Qué mensaje mío reconoces sin mirar el nombre?",
    "¿Qué te hace sentir acompañado/a cuando estamos lejos?",
    "¿Qué serie o película te recuerda a nosotros?",
    "¿Qué emoji nos representa?",
    "¿Qué comida te recuerda a mí?",
    "¿Qué canción parece escrita para nosotros?",
    "¿Qué situación cotidiana nos hace reír siempre?",
    "¿Qué momento compartido parece insignificante para otros pero no para nosotros?",
    "¿Qué rutina diaria te gustaría mantener siempre?",
    "¿Qué tema nunca nos cansamos de hablar?",
    "¿Qué actividad podríamos repetir mil veces?",
    "¿Qué costumbre surgió durante la distancia?",
    "¿Qué gesto mío te hace sentir cerca?",
    "¿Qué cosa hacemos mejor como equipo?",
    "¿Qué momento de nuestras videollamadas disfrutas más?",
    "¿Qué hábito compartido deberíamos inventar?",
    "¿Qué tradición te gustaría comenzar?",
    "¿Qué conversación parece eterna pero nunca aburrida?",
    "¿Qué hacemos diferente al resto de las parejas?",
    "¿Qué detalle cotidiano te enamora todavía?",
    "¿Qué momento simple describe mejor nuestra conexión?",
    "¿Qué aprendiste sobre el amor gracias a nosotros?",
    "¿Qué valoras más de mi forma de quererte?",
    "¿Qué crees que aporto a tu vida?",
    "¿Qué versión de ti aparece cuando estás conmigo?",
    "¿Qué admiras más de mí?",
    "¿Qué te hace sentir seguro/a en esta relación?",
    "¿Cuál es la lección más importante que hemos aprendido juntos?",
    "¿Qué aspecto de tu vida mejoró gracias a nuestra relación?",
    "¿Qué te gustaría que nunca cambiara entre nosotros?",
    "¿Qué significa para ti sentirte amado/a?",
    "¿Cuándo te has sentido más comprendido/a por mí?",
    "¿Qué fortaleza tenemos como pareja?",
    "¿Qué vulnerabilidad puedes mostrar conmigo?",
    "¿Qué emoción asocias más a nuestra historia?",
    "¿Qué cualidad mía te inspira?",
    "¿Qué te hace confiar en mí?",
    "¿Qué crees que hacemos bien cuando enfrentamos problemas?",
    "¿Qué parte de tu vida sería diferente sin mí?",
    "¿Qué sueño personal te gustaría compartir más conmigo?",
    "¿Qué te gustaría que entendiera mejor de ti?",
    "¿Qué significa para ti ser compañeros de vida?",
    "¿Qué es lo que más agradeces de nosotros?",
    "¿Qué miedo hemos superado juntos?",
    "¿Qué emoción te gustaría compartir más?",
    "¿Qué significa para ti la palabra hogar?",
    "¿Cuándo sentiste más orgullo de nosotros?",
    "¿Qué momento te hizo sentir profundamente amado/a?",
    "¿Qué cualidad nuestra nos hace únicos?",
    "¿Qué valor compartimos más intensamente?",
    "¿Qué aspecto de nuestra relación te da esperanza?",
    "¿Qué has descubierto sobre ti gracias a mí?",
    "¿Qué significa para ti nuestro apoyo mutuo?",
    "¿Qué sacrificio mutuo valoras más?",
    "¿Qué desafío nos fortaleció?",
    "¿Qué emoción positiva te genera pensar en nuestro futuro?",
    "¿Qué sueño te emociona compartir conmigo?",
    "¿Qué cualidad tuya crees que floreció gracias a nuestra relación?",
    "¿Qué palabra define mejor nuestro vínculo?",
    "¿Qué te gustaría agradecerme hoy?",
    "¿Qué sentimiento resume nuestra historia?",
    "¿Cómo imaginas nuestro próximo reencuentro?",
    "¿Qué lugar sueñas visitar conmigo?",
    "¿Qué experiencia te gustaría vivir juntos al menos una vez?",
    "¿Cómo imaginas un día perfecto juntos?",
    "¿Qué sueño compartido te emociona más?",
    "¿Qué aventura deberíamos planear pronto?",
    "¿Dónde te gustaría celebrar un aniversario importante?",
    "¿Qué proyecto te gustaría construir juntos?",
    "¿Cómo imaginas nuestra vida dentro de cinco años?",
    "¿Qué hábito nos ayudaría a acercarnos a nuestros sueños?",
    "¿Qué país deberíamos conocer juntos?",
    "¿Qué experiencia romántica está pendiente?",
    "¿Qué tradición futura te gustaría crear?",
    "¿Qué meta deberíamos alcanzar como equipo?",
    "¿Qué tipo de hogar imaginas?",
    "¿Qué ciudad te gustaría explorar conmigo?",
    "¿Qué aventura espontánea deberíamos vivir?",
    "¿Qué sueño parece imposible pero vale la pena intentar?",
    "¿Qué experiencia te gustaría regalarme?",
    "¿Qué experiencia te gustaría que yo te regalara?",
    "¿Cómo imaginas nuestros fines de semana ideales?",
    "¿Qué lista de deseos deberíamos crear?",
    "¿Qué aprendizaje te gustaría vivir juntos?",
    "¿Qué proyecto creativo haríamos bien?",
    "¿Qué viaje repetiríamos varias veces?",
    "¿Qué experiencia nos haría crecer más?",
    "¿Qué sueño compartido te parece más emocionante?",
    "¿Cómo imaginas nuestro aniversario número veinte?",
    "¿Qué recuerdo futuro quieres empezar a construir ya?",
    "¿Qué aventura debería ocurrir este año?",
    "¿Qué celebración imaginaria organizarías para nosotros?",
    "¿Qué sueño personal quieres que apoyemos juntos?",
    "¿Qué lugar del mundo te recuerda a nosotros?",
    "¿Qué meta te gustaría alcanzar conmigo?",
    "¿Qué experiencia extrema te animarías a vivir juntos?",
    "¿Cómo te imaginas nuestras vacaciones perfectas?",
    "¿Qué historia quieres que contemos en el futuro?",
    "¿Qué momento futuro te emociona más esperar?",
    "¿Qué deseo compartido aún no hemos dicho en voz alta?",
    "¿Qué legado te gustaría construir juntos?",
    "¿Qué preferirías: leer mi mente o que yo lea la tuya?",
    "¿Quién sobreviviría más tiempo en una isla desierta?",
    "¿Quién gastaría primero un millón de dólares?",
    "¿Qué superpoder sería perfecto para nuestra relación?",
    "¿Quién ganaría una competencia de terquedad?",
    "¿Qué animal representa mejor nuestra pareja?",
    "¿Qué personaje ficticio se parece más a nosotros?",
    "¿Qué harías si aparezco de sorpresa en tu puerta ahora mismo?",
    "¿Qué emoji sería nuestro escudo oficial?",
    "¿Quién sería peor espía?",
    "¿Qué sería más peligroso: cocinar juntos o armar muebles juntos?",
    "¿Qué nombre tendría nuestra sitcom?",
    "¿Qué concurso de televisión podríamos ganar?",
    "¿Quién perdería primero en un juego de silencio?",
    "¿Qué ley absurda tendría nuestro país imaginario?",
    "¿Qué castigo gracioso pondrías por olvidar fechas?",
    "¿Qué habilidad inútil nos haría millonarios?",
    "¿Qué harías si un genio te concede un deseo para nosotros?",
    "¿Quién tiene más probabilidades de iniciar una aventura accidental?",
    "¿Qué haríamos si quedamos encerrados en un supermercado toda la noche?",
    "¿Qué haríamos si ganamos la lotería mañana?",
    "¿Qué objeto cotidiano representa nuestra relación?",
    "¿Qué apodo ridículamente cursi nos pondríamos?",
    "¿Qué haríamos en un apocalipsis zombie?",
    "¿Qué harías si solo pudiéramos comunicarnos con memes durante una semana?",
    "¿Qué trabajo extraño podríamos hacer juntos?",
    "¿Qué harías si descubres que soy un extraterrestre?",
    "¿Qué sería más difícil: no hablarme una semana o no usar internet una semana?",
    "¿Qué invento absurdo crearíamos?",
    "¿Quién ganaría una competencia de memes?",
    "¿Qué título tendría nuestro reality show?",
    "¿Qué harías si nos vuelven personajes de dibujos animados?",
    "¿Qué objeto salvarías primero de nuestra historia?",
    "¿Qué tres cosas llevaríamos a una isla desierta?",
    "¿Qué sería más divertido: viajar al pasado o al futuro juntos?",
    "¿Qué misión imposible aceptaríamos como equipo?",
    "¿Cuál es tu amistad íntima más reciente?",
    "¿En qué cambiaste de opinión?",
    "¿Qué te hace reír?",
    "¿Cuál fue el mejor regalo que hiciste?",
    "¿Qué otra persona te gustaría ser por un día?",
    "¿Qué harías si pudieras tomarte un año sabático?",
    "¿Cuál fue el viaje más memorable que hiciste?",
    "¿Qué canción te hace sentir bien?",
    "¿Qué sabés hoy que te hubiera gustado saber años atrás?",
    "¿Qué norma social eliminarías?",
    "¿Qué hábito te gustaría incorporar en tu vida?",
    "¿De qué te arrepentís?",
    "¿Qué harías si supieras que no vas a fracasar?",
    "¿Cuál fue la decisión más difícil que tomaste?",
    "¿Cuál fue el mejor reconocimiento que recibiste en tu vida?",
    "¿Cómo nacieron tus pasiones?",
    "¿Cuál fue el mayor ataque de risa de tu vida?",
    "¿Qué superpoder te gustaría tener?",
    "¿Qué docentes u otras personas te influyeron profundamente?",
    "¿Cuál es la locura más grande que hiciste en tu vida?",
    "¿Qué te enoja?",
    "¿Qué no te gusta de vos y estás trabajando en cambiar?",
    "¿Qué características sentís que tenés de las personas que te criaron?",
    "¿Cuál sentís que es la invención más importante de los últimos 2000 años?",
    "¿Qué es lo más importante que tenés en la lista de pendientes para tu vida?",
    "¿Qué es lo más bello que creaste en tu vida?",
    "¿Cuál fue el mayor papelón de tu vida?",
    "¿Qué sueños de tu infancia se hicieron realidad? ¿Cuáles no?",
    "¿Cuál fue la conversación más difícil que tuviste en tu vida?",
    "¿En qué sentís que opinás distinto a la gente que te rodea?",
    "¿Qué frase sentís que condensa lo más importante de la sabiduría humana?",
    "¿Qué querrías lograr el año que viene?",
    "¿Qué aprendiste porque sí, es decir, sin una necesidad concreta?",
    "¿Qué te gustaría dejar de hacer?",
    "¿Qué harías distinto hoy, si supieras que te quedan 5 años de vida?",
    "¿Qué cosas no te perdonás?",
    "¿En qué sos optimista?",
    "¿Qué pregunta ya no te hacés más?",
    "¿Qué te gustaría saber pero no querés dedicarle el tiempo y esfuerzo para aprender?",
    "¿Qué vivencias de la niñez te marcaron?",
    "¿Qué harías si no tuvieras que trabajar para ganar dinero?",
    "¿Con quién te gustaría compartir un proyecto?",
    "¿Con quiénes te sentís bien estando en silencio?",
    "¿Qué le preguntarías a un extraterrestre?",
    "¿Cuál fue el mejor regalo que recibiste?",
    "¿Cuándo fue la última vez que hiciste algo por primera vez?",
    "¿Qué olor o aroma te recuerda un momento importante de tu vida?",
    "¿Cuál fue tu primer amor?",
    "¿Sentís que tenés un propósito en la vida? ¿Cuál es?",
    "¿Tenés alguna habilidad inútil? ¿Cuál es?",
    "¿Cuál es tu hábito actual favorito?",
    "¿Qué actividad te hace perder la noción del tiempo?",
    "¿Qué debería enseñarse en las escuelas que no se está enseñando?",
    "¿Por qué aspectos de tu vida sentís gratitud?",
    "¿Qué no entienden las generaciones mayores o menores a vos?",
    "¿Qué querés hacer antes de que termine el día de hoy?",
    "¿Cuál es el mejor consejo que te han dado?",
    "¿Qué diría tu etiquetado frontal? Es decir, ¿qué deberían saber de vos las otras personas?",
    "¿Qué aspectos de tu personalidad de la infancia tenés todavía hoy?",
    "¿Qué cosas innecesarias acumulás?",
    "¿Cuándo sentís que estás usando bien tu tiempo?",
    "¿Qué te asombra? ¿Cuáles son esas cosas que ves y decís ¡guau!?",
    "¿Cuáles son los libros, series o películas que más te impactaron en la vida?",
    "¿Estás priorizando lo que considerás más importante en tu vida?",
    "¿Cuál es la anécdota que más te gusta contar?",
    "¿Qué te gustaría aprender que no sabés todavía?",
    "¿Cuál fue el riesgo más grande que tomaste en tu vida?",
    "¿En qué momentos sentís que tu vida es plena?",
    "¿Qué lograste que no creías posible?",
    "¿En qué sentís que sos una persona creativa?",
    "¿Cuál fue la situación más extrema a la que te enfrentaste?",
    "¿Cuándo fue la última vez que lloraste?",
    "¿Qué es lo más importante que aprendiste haciendo lo que hacés?",
    "¿De qué tenés miedo?",
    "¿Qué dijiste que nunca harías y terminaste haciendo?",
    "¿Con qué figura histórica te gustaría ir a cenar?",
    "¿Creés en algo que no puedas demostrar?",
    "¿Con qué estás procrastinando (postponiendo más de lo que deberías)?",
    "¿De qué aspecto de tu vida sentís orgullo?",
    "¿Qué le dirías a tu yo de dentro de 10 años?",
    "¿Qué nuevo invento necesitamos?",
    "¿Cómo sería tu trabajo ideal?",
    "¿Cuál creés que es la noticia reciente más interesante?",
    "¿Qué te quita el sueño?",
    "¿Qué concepto o idea debería conocerse más?",
    "¿Qué harías distinto hoy, si supieras que vas a vivir 200 años?",
    "¿Qué pregunta te hacés todo el tiempo?",
    "¿Tus hábitos están alineados con lo que querés lograr en tu vida?",
    "¿Cuándo fue la última vez que le alegraste el día a alguien?",
    "Nos despertamos mañana y tenemos un millón de dólares. ¿Qué hacés primero?",
    "Sólo podemos comer una comida durante un año. ¿Cuál elegís y por qué?",
    "Tenemos que vivir un mes en otro país, sin elegir cuál. ¿Cómo te imaginás?",
    "Intercambiamos cuerpos durante 24 horas. ¿Qué es lo primero que hacés en el mío?",
    "Podemos borrar un solo recuerdo de nuestra historia. ¿Lo harías? ¿Cuál?",
    "Un extraterrestre nos invita a viajar con él, sin garantía de volver. ¿Vas?",
    "Tenemos que comunicarnos sólo con memes durante una semana. ¿Cómo te va?",
    "Ganamos un viaje a cualquier lugar del mundo, pero sale mañana. ¿A dónde?",
    "Nos ofrecen saber el día exacto en que vamos a morir. ¿Querés saberlo?",
    "Podemos pausar el tiempo por un día entero, solo para nosotros. ¿Qué hacemos?",
    "Tenemos que elegir un superpoder para toda la vida. ¿Cuál y por qué?",
    "Nos regalan una casa, pero en el lugar más random del mundo. ¿La aceptás?",
    "Un genio te concede un deseo, pero sólo si es para los dos. ¿Qué pedís?",
    "Nos quedamos sin batería de celular por una semana entera. ¿Cómo seguimos?",
    "Podemos revivir un solo día de nuestra historia juntos. ¿Cuál elegís?",
    "Nos ofrecen fama mundial a cambio de nunca más vernos en persona. ¿Aceptás?",
    "Tenemos que mudarnos juntos mañana mismo, sin planear nada. ¿Cómo reaccionás?",
    "Podés cambiar una decisión del pasado sin consecuencias. ¿Cuál cambiarías?",
    "Nos regalan una máquina del tiempo, un solo viaje. ¿A qué momento nuestro volverías?",
    "Si hoy fuera el último día para decirme algo, ¿qué me dirías?",
    "Nos despertamos y ya no existe la distancia entre nosotros. ¿Qué hacés en la primera hora?",
    "Tenemos que elegir entre no volver a discutir nunca o no volver a reírnos juntos. ¿Qué elegís?",
    "Un hada te da la posibilidad de saber qué piensa el otro por un día. ¿La usarías?",
    "Si mañana perdiéramos todo lo material pero nos tuviéramos a nosotros, ¿cómo seguirías?",
    "Podemos elegir vivir en cualquier época de la historia, juntos. ¿Cuál elegirías?",
    "Si tuvieras que convencerme de algo importante en 30 segundos, ¿qué me dirías?",
    "Nos ofrecen la posibilidad de saber si en 5 años seguimos juntos. ¿Preguntarías?",
    "Si sólo pudieras salvar una foto nuestra de un incendio, ¿cuál sería?",
    "Tenemos que dar una charla TED sobre nuestra relación mañana. ¿De qué hablarías?",
    "Si pudieras vivir un año entero sin trabajar, ¿qué harías conmigo ese año?",
    "Nos dan la opción de vivir para siempre jóvenes pero sin poder tener hijos. ¿La tomás?",
    "Si tu yo del futuro te mandara un mensaje hoy, ¿qué creés que diría sobre nosotros?",
    "Tenemos que elegir un país para nunca más poder visitar. ¿Cuál sacrificás?",
    "Si pudieras hacerme una sola pregunta y yo tuviera que responder 100% honesto, ¿cuál sería?",
    "Nos regalan boletos para el primer vuelo comercial a la Luna. ¿Vamos?",
    "Si tuvieras que resumir nuestra relación en una película, ¿qué género sería y por qué?",
    "Podés elegir un talento nuevo para mí. ¿Cuál me darías?",
    "Si esta fuera la última semana de la distancia antes de vivir juntos para siempre, ¿qué harías distinto?",
    "Nos dan a elegir entre vivir 100 años separados o 20 años juntos. ¿Qué elegís?",
    "Si pudieras escuchar el pensamiento que tuve hoy sobre vos, ¿te gustaría saberlo ahora?",
    "Tenemos que dejar todo y mudarnos a un barco por un año. ¿Cómo te la imaginás?",
    "Si pudieras vivir dentro de un recuerdo nuestro por un día, ¿cuál elegirías?",
    "Nos ofrecen la chance de conocer a nuestros hijos del futuro por 10 minutos. ¿Querés?",
    "Si tuvieras que enseñarme algo de tu cultura en un día, ¿qué elegirías?",
    "Tenemos que elegir entre perder el sentido del humor o la memoria de corto plazo. ¿Qué eligís?",
    "Si pudieras hacer que dejemos de pelear por un tema específico para siempre, ¿cuál sería?",
    "Nos regalan la casa de nuestros sueños pero en un lugar sin internet. ¿La aceptás?",
    "Si mañana tuviéramos que decidir en qué ciudad vivir para siempre, ¿cuál proponés?",
    "Tenemos que elegir un objeto que represente nuestra relación para meter en una cápsula del tiempo. ¿Cuál?",
    "Si pudieras vivir sin dormir pero sin cansarte, ¿qué harías con esas horas extra conmigo?",
    "Nos dan la chance de reescribir el día en que nos conocimos. ¿Cambiarías algo?",
    "Si tuvieras que elegir entre perder todos tus recuerdos de otras personas o de mí, ¿qué elegirías conservar?",
    "Tenemos que sobrevivir un mes con lo que hay en la heladera de cada uno. ¿Cómo nos va?",
    "Si pudieras teletransportarte a mi lado ahora mismo por sólo una hora, ¿qué haríamos?",
    "Nos ofrecen viajar en el tiempo hasta el día en que naciste. ¿Irías a verte de bebé?",
    "Si tuvieras que dejar un mensaje de voz para que lo escuche dentro de 10 años, ¿qué dirías?",
    "Tenemos que elegir un superpoder colectivo para la pareja. ¿Cuál sería el más útil para nosotros?",
    "Si pudieras vivir en cualquier libro o película con nosotros como protagonistas, ¿cuál elegirías?",
    "Nos regalan un año sabático para hacer lo que queramos. ¿Qué harías vos?",
    "Si tuvieras que elegir entre tener razón siempre o ser feliz siempre, ¿qué elegís?",
    "Tenemos que decidir juntos si mudarnos a la ciudad o al campo para siempre. ¿Qué elegís?",
    "Si pudieras ver un solo día de mi futuro sin mí en él, ¿lo mirarías?",
    "Nos ofrecen borrar la palabra 'no' de nuestro vocabulario por una semana. ¿Aceptás?",
    "Si tuvieras que dar un discurso en nuestra boda (real o imaginaria), ¿qué dirías?",
    "Tenemos que elegir vivir un mes sin ningún tipo de tecnología. ¿Cómo te la imaginás?",
    "Si pudieras cambiar el clima de donde vivo para que se parezca más al tuyo, ¿lo harías?",
    "Nos regalan la posibilidad de aprender el idioma del otro perfectamente en un día. ¿Lo usarías?",
    "Si tuvieras que elegir un animal que nos represente como pareja, ¿cuál sería?",
    "Tenemos que armar un plan de escape si el mundo se termina mañana. ¿Cuál sería?",
    "Si pudieras saber qué pensaba de vos la primera vez que me viste (sin preguntarme), ¿te gustaría?",
    "Nos ofrecen vivir literalmente dentro de nuestras fotos favoritas por un rato. ¿Cuál elegís?",
    "Si tuvieras que elegir entre perder la vista o el oído, sabiendo que seguiríamos juntos, ¿qué elegís?",
    "Tenemos que preparar una cápsula del tiempo para abrir en 20 años. ¿Qué meterías?",
    "Si pudieras cambiar un hábito mío con un chasquido de dedos, ¿lo harías?",
    "Nos dan a elegir entre un mes de vacaciones ilimitadas o un aumento enorme de sueldo. ¿Qué elegís?",
    "Si tuvieras que mudarte de continente mañana sin avisar a nadie, ¿lo harías por mí?",
    "Tenemos que sobrevivir un fin de semana sin hablar, sólo con gestos. ¿Cómo nos va?",
    "Si pudieras vivir literalmente adentro de una canción que nos representa, ¿cuál elegirías?",
    "Nos regalan la chance de conocer a nuestras versiones de hace 10 años. ¿Qué les dirías?",
    "Si tuvieras que elegir un lugar del mundo para pedirme matrimonio (hipotéticamente), ¿cuál sería?",
    "Tenemos que decidir entre vivir sin dinero pero felices, o con mucho dinero pero estresados. ¿Qué elegís?",
    "Si pudieras escuchar la voz de nuestro 'nosotros' del futuro dándonos un consejo, ¿qué creés que diría?",
    "Nos ofrecen la posibilidad de repetir nuestra primera cita exactamente igual. ¿La repetirías?",
    "Si tuvieras que elegir el soundtrack de nuestra vida juntos, ¿qué tres canciones no podrían faltar?",
    "Tenemos que decidir si mudarnos apenas podamos o esperar el momento 'perfecto'. ¿Qué elegís?",
    "Si pudieras ver el final de nuestra historia ahora mismo, ¿querrías saberlo?",
    "Nos regalan la chance de vivir un día entero como el otro, viendo el mundo con sus ojos. ¿Lo harías?",
    "Si tuvieras que elegir una sola virtud tuya para dejarme como herencia, ¿cuál sería?",
    "Tenemos que planear el reencuentro perfecto sin límite de presupuesto. ¿Cómo sería?",
    "Si pudieras vivir sabiendo que cada 'te amo' es literal y con peso real, ¿lo dirías más seguido?",
    "Nos ofrecen intercambiar un miedo tuyo por uno mío. ¿Lo harías?",
    "Si tuvieras que elegir el lugar exacto donde vivir juntos para siempre, ahora mismo, ¿cuál sería?",
    "Tenemos que decidir si mudarnos cerca de tu familia o de la mía. ¿Qué proponés?",
    "Si pudieras congelar un momento nuestro para vivir en loop por una semana, ¿cuál elegirías?",
    "Nos regalan la posibilidad de saber la verdad absoluta sobre cualquier duda que tengas de mí. ¿La usarías?",
    "Si tuvieras que resumir en una palabra lo que sentís ahora mismo por nosotros, ¿cuál sería?",
    "Tenemos que decidir entre tener una vida tranquila y predecible, o una llena de sorpresas y riesgo. ¿Qué elegís?",
    "Si pudieras hacer que un miedo mío desaparezca para siempre, ¿cuál elegirías borrar?",
    "Nos ofrecen vivir 100 vidas distintas, pero sólo si en cada una nos volvemos a encontrar. ¿Aceptás?",
    "Si tuvieras que elegir el nombre de nuestra futura mascota o hijo/a ahora mismo, ¿cuál sería?",
    "¿Dónde te gustaría que viviéramos en unos años?",
    "¿Cómo sería una noche cualquiera dentro de 5 años, para vos?",
    "¿Qué hábito deberíamos construir juntos desde ya?",
    "¿Qué aventura grande deberíamos vivir alguna vez?",
    "¿Qué cosa de lo que tenemos hoy jamás deberíamos perder?",
    "¿Cómo te imaginás nuestros domingos en el futuro?",
    "¿Qué tipo de familia o vida en común te imaginás?",
    "¿Qué tradición nueva te gustaría que empecemos?",
    "¿Cómo nos imaginás discutiendo (si es que discutimos) en el futuro?",
    "¿Qué versión de nosotros te gustaría ver dentro de 10 años?",
    "¿Cómo te gustaría que fuera nuestra casa dentro de 5 años?",
    "¿Qué trabajo o proyecto te gustaría estar haciendo en el futuro?",
    "¿Cómo te imaginás nuestras vacaciones ideales dentro de unos años?",
    "¿Qué te gustaría que la gente dijera de nosotros como pareja en el futuro?",
    "¿Cómo te imaginás celebrando nuestro décimo aniversario?",
    "¿Qué proyecto en común te gustaría empezar el año que viene?",
    "¿Cómo te gustaría que fueran nuestras mañanas si viviéramos juntos?",
    "¿Qué lugar del mundo te gustaría que sea 'nuestro' con el tiempo?",
    "¿Cómo te imaginás pasando las fiestas de fin de año en el futuro?",
    "¿Qué te gustaría que aprendiéramos juntos en los próximos años?",
    "¿Cómo te imaginás nuestra rutina de fin de semana ideal, más adelante?",
    "¿Qué te gustaría que fuera distinto en nosotros dentro de un año?",
    "¿Cómo te imaginás nuestra comunicación cuando ya no haya distancia?",
    "¿Qué costumbre de tu familia te gustaría traer a nuestra futura vida juntos?",
    "¿Cómo te imaginás nuestra mascota ideal, si tuviéramos una?",
    "¿Qué te gustaría lograr como equipo en los próximos 3 años?",
    "¿Cómo te imaginás nuestro primer departamento juntos?",
    "¿Qué actividad te gustaría que hagamos juntos todas las semanas en el futuro?",
    "¿Cómo te imaginás nuestras conversaciones dentro de 20 años?",
    "¿Qué te gustaría que supiéramos hacer juntos que hoy no sabemos?",
    "¿Cómo te imaginás festejando un logro grande de alguno de los dos, en el futuro?",
    "¿Qué te gustaría que representara nuestra casa cuando la tengamos?",
    "¿Cómo te imaginás pasando un día de enfermedad, cuidándonos mutuamente en persona?",
    "¿Qué te gustaría enseñarme en el futuro que hoy no sé?",
    "¿Cómo te imaginás nuestro círculo de amigos en común dentro de unos años?",
    "¿Qué te gustaría que digamos siempre, como frase propia de nosotros?",
    "¿Cómo te imaginás nuestras discusiones resueltas en el futuro, comparadas con hoy?",
    "¿Qué te gustaría construir juntos que no sea material?",
    "¿Cómo te imaginás el día que finalmente vivamos en la misma ciudad?",
    "¿Qué costumbre nueva te gustaría empezar el día que estemos juntos definitivamente?",
    "¿Cómo te imaginás nuestras conversaciones sobre el futuro dentro de 5 años, comparadas con hoy?",
    "¿Qué te gustaría que hiciéramos juntos por primera vez el año que viene?",
    "¿Cómo te imaginás nuestro equipo frente a una crisis futura?",
    "¿Qué tipo de padres (si algún día lo somos) te gustaría que seamos?",
    "¿Cómo te imaginás nuestras charlas de sobremesa dentro de 10 años?",
    "¿Qué te gustaría que valoremos más con el paso del tiempo?",
    "¿Cómo te imaginás nuestra forma de festejar los pequeños logros del día a día, en el futuro?",
    "¿Qué te gustaría que sea innegociable en nuestra vida juntos, pase lo que pase?",
    "¿Cómo te imaginás nuestras vacaciones cuando ya no tengamos que ahorrar para los pasajes?",
    "¿Qué te gustaría que fuera parte de nuestra rutina diaria en el futuro?",
    "¿Cómo te imaginás cuidándonos mutuamente cuando seamos grandes?",
    "¿Qué te gustaría que aprendamos el uno del otro con el tiempo?",
    "¿Cómo te imaginás nuestra primera pelea después de vivir juntos, y cómo la resolvemos?",
    "¿Qué te gustaría que fuera distinto de tu vida actual, gracias a nosotros, en 5 años?",
    "¿Cómo te imaginás celebrando un cumpleaños tuyo dentro de 10 años?",
    "¿Qué te gustaría que hiciéramos juntos los domingos de lluvia, en el futuro?",
    "¿Cómo te imaginás nuestra vida social como pareja, más adelante?",
    "¿Qué te gustaría que representemos como pareja para la gente que nos rodea?",
    "¿Cómo te imaginás nuestro primer viaje largo juntos, sin límite de presupuesto?",
    "¿Qué te gustaría que fuera parte de nuestra decoración en la futura casa?",
    "¿Cómo te imaginás resolviendo decisiones grandes de dinero en el futuro?",
    "¿Qué te gustaría que aprendiéramos a cocinar juntos con el tiempo?",
    "¿Cómo te imaginás nuestras noches de películas dentro de unos años?",
    "¿Qué te gustaría que fuera nuestra 'canción' oficial de acá a un tiempo?",
    "¿Cómo te imaginás celebrando el día que finalmente no haya más distancia?",
    "¿Qué te gustaría que hagamos juntos una vez al año, sin falta, para siempre?",
    "¿Cómo te imaginás nuestras conversaciones sobre tener hijos, en el futuro?",
    "¿Qué te gustaría que fuera un ritual exclusivo nuestro, con el tiempo?",
    "¿Cómo te imaginás apoyándonos en un momento difícil, dentro de unos años?",
    "¿Qué te gustaría que hiciéramos distinto la próxima vez que discutamos?",
    "¿Cómo te imaginás nuestras charlas filosóficas dentro de 15 años?",
    "¿Qué te gustaría que fuera parte de nuestra identidad como pareja, siempre?",
    "¿Cómo te imaginás enseñándole algo tuyo a nuestro futuro entorno (hijos, sobrinos, etc.)?",
    "¿Qué te gustaría lograr individualmente, sabiendo que voy a estar ahí para apoyarte?",
    "¿Cómo te imaginás nuestras rutinas de autocuidado compartidas en el futuro?",
    "¿Qué te gustaría que aprendamos sobre comunicación con el paso de los años?",
    "¿Cómo te imaginás celebrando nuestros 25 años juntos, si llegamos ahí?",
    "¿Qué te gustaría que hiciéramos la primera semana que vivamos juntos?",
    "¿Cómo te imaginás nuestro balance entre trabajo y tiempo juntos, en el futuro?",
    "¿Qué te gustaría que sea distinto en la forma en que nos cuidamos, con el tiempo?",
    "¿Cómo te imaginás pasando una Navidad o Año Nuevo con las dos familias juntas?",
    "¿Qué te gustaría que representemos para las próximas generaciones de nuestra familia?",
    "¿Cómo te imaginás nuestro primer gran desacuerdo importante ya viviendo juntos?",
    "¿Qué te gustaría que fuera parte de nuestros hobbies compartidos, en el futuro?",
    "¿Cómo te imaginás apoyándome en un proyecto grande mío, más adelante?",
    "¿Qué te gustaría que sintamos al mirar atrás, dentro de 10 años, sobre esta etapa de distancia?",
    "¿Cómo te imaginás nuestras conversaciones cuando ya no haya nada que ocultar ni explicar?",
    "¿Qué te gustaría que aprendiéramos a soltar, con el tiempo?",
    "¿Cómo te imaginás nuestro primer 'hogar' de verdad, sea donde sea?",
    "¿Qué te gustaría que perdure de nosotros, pase lo que pase en el futuro?",
    "¿Cómo te imaginás la primera vez que alguien nos pregunte 'hace cuánto están juntos' y contemos toda la historia?",
    "¿Qué te gustaría lograr juntos que hoy parece imposible?",
    "¿Cómo te imaginás nuestras charlas sobre el pasado, dentro de muchos años?",
    "¿Qué te gustaría que fuera un símbolo de esta etapa a distancia, en el futuro?",
    "¿Cómo te imaginás cuidando de mí en un momento de mucho estrés, más adelante?",
    "¿Qué te gustaría construir juntos que dure más que nosotros?",
    "¿Cómo te imaginás la primera Navidad que pasemos juntos, en persona?",
    "¿Qué te gustaría que aprenda de vos en los próximos años?",
    "¿Cómo te imaginás nuestra vida cuando ya no tengamos que contar los días para vernos?",
    "¿Qué te gustaría agradecerle a esta etapa de distancia, mirando hacia atrás en el futuro?",
    "Contá cómo recordás nuestro primer mensaje.",
    "Contá cómo recordás nuestro primer encuentro en persona.",
    "Contá cuál fue tu momento favorito juntos, y por qué.",
    "Contá cuál fue el momento más difícil que atravesamos juntos.",
    "Contá qué momento repetirías exactamente igual si pudieras.",
    "Contá qué momento cambiarías si pudieras, y cómo.",
    "Contá cómo recordás la primera vez que te dije 'te quiero' (o algo parecido).",
    "Contá cómo recordás nuestra primera videollamada larga.",
    "Contá cómo recordás el día que decidimos ponerle nombre a esto.",
    "Contá cómo recordás la primera vez que discutimos en serio.",
    "Contá cómo recordás la primera vez que te presenté (o me presentaste) a tu familia o amigos.",
    "Contá cómo recordás el día que hablamos de un futuro juntos por primera vez.",
    "Contá cómo recordás la despedida de nuestro primer encuentro en persona.",
    "Contá cómo recordás la primera semana después de conocernos.",
    "Contá cómo recordás el momento en que sentiste que esto iba en serio.",
    "Contá cómo recordás una noche cualquiera de charla que se hizo larga sin darnos cuenta.",
    "Contá cómo recordás el día que superamos un mal entendido grande.",
    "Contá cómo recordás la primera vez que lloraste (de alegría o de tristeza) por nosotros.",
    "Contá cómo recordás el primer regalo que nos hicimos.",
    "Contá cómo recordás la primera vez que dijimos 'te extraño' en serio.",
    "Contá cómo recordás un momento en el que sentiste que el otro te entendía sin explicar nada.",
    "Contá cómo recordás la primera pelea que resolvimos bien.",
    "Contá cómo recordás el día en que planeamos nuestro primer viaje juntos.",
    "Contá cómo recordás una charla nocturna que te marcó.",
    "Contá cómo recordás el momento en que sentiste más orgullo del otro.",
    "Contá cómo recordás la primera vez que nos reímos hasta llorar juntos.",
    "Contá cómo recordás un silencio cómodo que tuvimos alguna vez.",
    "Contá cómo recordás la primera vez que hablamos de nuestros miedos.",
    "Contá cómo recordás el día que uno de los dos tuvo un mal día y el otro lo sostuvo.",
    "Contá cómo recordás una charla sobre el futuro que te dio ilusión.",
    "Contá cómo recordás la primera canción que asociaste con nosotros.",
    "Contá cómo recordás el momento en que decidiste confiar del todo en el otro.",
    "Contá cómo recordás una foto o video que nos sacamos y por qué te gusta.",
    "Contá cómo recordás el día que nos dijimos algo difícil pero necesario.",
    "Contá cómo recordás la primera vez que sentiste celos, si pasó.",
    "Contá cómo recordás una charla filosófica o profunda que tuvimos.",
    "Contá cómo recordás la primera vez que hicimos un plan a largo plazo juntos.",
    "Contá cómo recordás la sensación de la última despedida antes de separarnos por la distancia.",
    "Contá cómo recordás el momento en que te diste cuenta de que me extrañabas de verdad.",
    "Contá cómo recordás una charla random que terminó siendo importante.",
    "Contá cómo recordás el día que hablamos de mudarnos juntos por primera vez.",
    "Contá cómo recordás una vez que te sorprendí (o me sorprendiste) sin avisar.",
    "Contá cómo recordás la primera vez que hablamos de nuestro pasado sentimental.",
    "Contá cómo recordás un momento incómodo que después se volvió gracioso.",
    "Contá cómo recordás la vez que uno de los dos casi cancela un plan importante.",
    "Contá cómo recordás la primera vez que nos enojamos por celos.",
    "Contá cómo recordás un consejo que me diste (o te di) que te cambió algo.",
    "Contá cómo recordás la primera vez que hablamos de tener hijos o no.",
    "Contá cómo recordás un momento de vulnerabilidad total del otro.",
    "Contá cómo recordás la primera vez que sentiste que 'esto es distinto a todo lo anterior'.",
    "Contá cómo recordás una charla sobre nuestros respectivos trabajos o estudios.",
    "Contá cómo recordás la primera vez que uno cuidó al otro estando enfermo, aunque sea a la distancia.",
    "Contá cómo recordás el día que hablamos de qué significa el amor para cada uno.",
    "Contá cómo recordás una charla sobre nuestras familias.",
    "Contá cómo recordás la primera vez que dijimos 'esto vale la pena' en voz alta.",
    "Contá cómo recordás una charla sobre nuestros defectos, sin pelear.",
    "Contá cómo recordás el día que decidiste que ibas a esperar, pase lo que pase.",
    "Contá cómo recordás una charla sobre celos o inseguridades que tuvimos.",
    "Contá cómo recordás la primera vez que uno defendió al otro frente a alguien más.",
    "Contá cómo recordás un chiste interno que nació de la nada.",
    "Contá cómo recordás la primera vez que hablamos en otro idioma entre nosotros, si pasó.",
    "Contá cómo recordás el día que uno de los dos dudó de la relación, si pasó.",
    "Contá cómo recordás la primera vez que planeamos algo para el futuro cercano juntos.",
    "Contá cómo recordás una charla sobre nuestros sueños personales, no en pareja.",
    "Contá cómo recordás la primera vez que nos mandamos una foto sin arreglar, tal cual estábamos.",
    "Contá cómo recordás la sensación de contarle a otra persona sobre nosotros por primera vez.",
    "Contá cómo recordás un día común, sin nada especial, que igual se sintió lindo.",
    "Contá cómo recordás la primera vez que hablamos de mudarnos de país.",
    "Contá cómo recordás una charla en la que uno cambió de opinión gracias al otro.",
    "Contá cómo recordás la primera vez que sentiste que podías ser 100% vos mismo/a conmigo.",
    "Contá cómo recordás una noche que no pudimos hablar por algún motivo, y cómo se sintió.",
    "Contá cómo recordás la vez que uno se disculpó primero sin que el otro lo pidiera.",
    "Contá cómo recordás la primera vez que hablamos de nuestras rutinas diarias.",
    "Contá cómo recordás una charla sobre qué esperamos del otro en una pelea.",
    "Contá cómo recordás la primera vez que hablamos de plata o finanzas entre nosotros.",
    "Contá cómo recordás el día que nos prometimos algo y lo cumplimos.",
    "Contá cómo recordás una charla sobre lo que más nos gusta del otro físicamente.",
    "Contá cómo recordás la primera vez que uno lloró frente al otro por videollamada.",
    "Contá cómo recordás la sensación de contar los días para el próximo reencuentro.",
    "Contá cómo recordás una charla sobre qué haríamos si algo saliera mal.",
    "Contá cómo recordás el momento en que sentiste alivio de haberte animado a esto.",
    "Contá cómo recordás una charla sobre nuestros gustos musicales distintos (o parecidos).",
    "Contá cómo recordás la primera vez que uno le puso un límite sano al otro.",
    "Contá cómo recordás el día que hablamos de qué haríamos si algún día dejáramos de sentir lo mismo.",
    "Contá cómo recordás una charla nocturna sobre el sentido de la vida.",
    "Contá cómo recordás la primera vez que uno le agradeció al otro por algo específico.",
    "Contá cómo recordás una charla sobre nuestros miedos a la soledad.",
    "Contá cómo recordás la primera vez que hicimos algo 'de pareja' aunque estuviéramos lejos (ver algo juntos, cocinar lo mismo, etc.).",
    "Contá cómo recordás el momento en que entendiste algo importante sobre cómo ama el otro.",
    "Contá cómo recordás una charla sobre qué haríamos distinto si volviéramos a empezar.",
    "Contá cómo recordás la primera vez que uno mencionó la palabra 'para siempre'.",
    "Contá cómo recordás un mensaje que releíste muchas veces.",
    "Contá cómo recordás la primera vez que uno mostró una parte vulnerable que nunca había mostrado.",
    "Contá cómo recordás una charla sobre qué significa 'hogar' para cada uno.",
    "Contá cómo recordás el momento en que decidiste priorizar esta relación por sobre otras cosas.",
    "Contá cómo recordás una charla sobre lo que aprendimos de relaciones pasadas.",
    "Contá cómo recordás la primera vez que uno dijo 'no sé qué haría sin vos'.",
    "Contá cómo recordás un plan que hicimos y todavía no cumplimos, pero seguimos sosteniendo.",
    "Contá cómo recordás la primera vez que sentiste que esta relación te hacía mejor persona.",
    "Contá cómo recordás una charla difícil sobre el futuro que terminó bien.",
    "Contá cómo recordás la sensación exacta de la primera vez que nos abrazamos.",
    "Un momento conmigo que guardarías para siempre.",
    "Una escena de nuestros días juntos que repetirías tal cual fue.",
    "Un lugar al que te gustaría llevarme algún día.",
    "Una imagen (real o inventada) que representa nuestra relación.",
    "Un instante cotidiano que se sintió especial sin motivo aparente.",
    "Cómo te imaginás el día que finalmente vivamos juntos.",
    "Una escena que te gustaría que alguien pintara de nosotros.",
    "El momento exacto en el que sentiste que esto era serio.",
    "Una foto que te gustaría que existiera de nosotros, aunque no exista.",
    "Una escena de un reencuentro futuro, tal como te la imaginás.",
    "Un atardecer o amanecer que te gustaría vivir conmigo.",
    "Una escena cotidiana de una casa futura, imaginada con detalle.",
    "Un momento en el que sentiste que el tiempo se detenía.",
    "Una escena de nosotros riéndonos de algo tonto.",
    "Un lugar de tu ciudad que te gustaría fotografiar conmigo algún día.",
    "Una escena de comida compartida, real o imaginada, que te gusta pensar.",
    "Un momento de silencio compartido que fue lindo, no incómodo.",
    "Una escena de nosotros bailando, aunque sea mal.",
    "Un momento en el que te sentiste completamente vos mismo/a conmigo.",
    "Una escena que te gustaría enmarcar y colgar en nuestra futura casa.",
    "Un instante de ternura que recordás con claridad.",
    "Una escena imaginada de nosotros de viejos, juntos.",
    "Un momento en el que el otro te hizo sentir seguro/a.",
    "Una escena de un viaje futuro que te gustaría vivir conmigo.",
    "Un instante en el que sentiste orgullo del otro.",
    "Una escena de una discusión que terminó en abrazo.",
    "Un momento en una videollamada que se sintió como estar en persona.",
    "Una escena imaginada de presentarme (o presentarte) a tu familia.",
    "Un instante en el que la distancia se sintió más corta que nunca.",
    "Una escena de una mañana cualquiera que te gustaría vivir conmigo.",
    "Un momento donde el otro te hizo reír en medio de un mal día.",
    "Una escena imaginada de nuestra boda (aunque sea hipotética).",
    "Un instante donde sentiste gratitud pura por tenernos.",
    "Una escena de una noche estrellada que te gustaría compartir conmigo.",
    "Un momento donde uno cuidó al otro estando enfermo, aunque sea a la distancia.",
    "Una escena imaginada de la primera Navidad juntos en persona.",
    "Un instante donde sentiste que valía la pena todo el esfuerzo.",
    "Una escena de cocinar juntos, real o imaginada.",
    "Un momento donde uno sorprendió al otro sin aviso.",
    "Una escena imaginada de mudarnos juntos por primera vez.",
    "Un instante donde el otro te escuchó sin juzgar.",
    "Una escena de una caminata que te gustaría dar conmigo.",
    "Un momento donde sentiste que esto era diferente a todo lo anterior.",
    "Una escena imaginada de despertarnos juntos un domingo cualquiera.",
    "Un instante donde el otro te defendió o apoyó públicamente.",
    "Una escena de un festejo de cumpleaños, real o imaginado.",
    "Un momento donde el silencio dijo más que cualquier palabra.",
    "Una escena imaginada de una pelea de almohadas o algo igual de tonto.",
    "Un instante donde sentiste que esto iba a durar mucho tiempo.",
    "Una escena de nosotros mirando una serie o película juntos.",
    "Un momento donde el otro te hizo sentir menos solo/a.",
    "Una escena imaginada de un picnic en algún lugar bonito.",
    "Un instante donde te reíste tanto que te dolió la panza.",
    "Una escena de una charla profunda a la luz de las velas (real o imaginada).",
    "Un momento donde el otro dijo exactamente lo que necesitabas escuchar.",
    "Una escena imaginada de recibirme (o recibirte) en el aeropuerto.",
    "Un instante donde sentiste una conexión total sin decir nada.",
    "Una escena de nosotros bajo la lluvia, real o imaginada.",
    "Un momento donde el otro te hizo un gesto pequeño pero significativo.",
    "Una escena imaginada de una cena especial que nos gustaría vivir.",
    "Un instante donde te sentiste profundamente amado/a.",
    "Una escena de un abrazo que se sintió eterno.",
    "Un momento donde ambos nos reímos de un mal entendido, después de aclararlo.",
    "Una escena imaginada de un viaje en auto largo, escuchando música juntos.",
    "Un instante donde sentiste alivio de poder contarme algo difícil.",
    "Una escena de nosotros escribiéndonos cartas a mano, real o imaginada.",
    "Un momento donde el otro celebró un logro tuyo como si fuera propio.",
    "Una escena imaginada de nuestra primera Navidad con nuestra futura familia.",
    "Un instante donde sentiste que este amor te hacía mejor persona.",
    "Una escena de un juego o competencia tonta entre nosotros.",
    "Un momento donde uno esperó pacientemente al otro sin quejarse.",
    "Una escena imaginada de festejar un aniversario número diez.",
    "Un instante donde te sorprendió lo bien que me/te conocés a esta altura.",
    "Una escena de nosotros armando planes en una libreta o pizarra.",
    "Un momento donde sentiste que podías mostrar tu peor versión sin miedo.",
    "Una escena imaginada de un festejo sorpresa que te gustaría organizar.",
    "Un instante donde el otro te hizo sentir en casa, aunque estuviéramos lejos.",
    "Una escena de despedirnos en una terminal o aeropuerto, con toda la emoción.",
    "Un momento donde entendiste algo nuevo sobre el amor gracias a nosotros.",
    "Una escena imaginada de nuestra rutina diaria si viviéramos juntos.",
    "Un instante donde sentiste que la espera valía absolutamente la pena.",
    "Una escena de nosotros discutiendo sobre algo sin importancia y riéndonos después.",
    "Un momento donde el otro te hizo sentir escuchado/a de verdad.",
    "Una escena imaginada de un festejo de Año Nuevo juntos.",
    "Un instante donde sentiste que esto era 'para siempre', aunque sea por un segundo.",
    "Una escena de nosotros mirando fotos viejas juntos, ya siendo grandes.",
    "Un momento donde ambos coincidimos exactamente en lo mismo sin hablarlo.",
    "Una escena imaginada de nuestra casa con nuestras cosas mezcladas.",
    "Un instante donde el otro te sorprendió con algo que recordaba de una charla vieja.",
    "Una escena de festejar algo chiquito, como si fuera enorme.",
    "Un momento donde te diste cuenta de cuánto creciste gracias a esta relación.",
    "Una escena imaginada de un finde entero sin planes, sólo estando juntos.",
    "Un instante donde sentiste que ya no había vuelta atrás, y eso te dio paz.",
    "Una escena de nosotros mandándonos fotos random del día a día.",
    "Un momento donde el otro te hizo reír en el peor momento posible.",
    "Una escena imaginada de contarle a nuestros nietos cómo empezó todo.",
    "Un instante donde entendiste que este amor era distinto porque elegís, no porque es fácil.",
    "Una escena final, la que te gustaría que cerrara nuestra historia, mucho tiempo después.",
    "Una escena imaginada de despertarnos abrazados sin necesidad de despertador.",
    "Un instante donde sentiste que ya éramos, sin dudas, un equipo.",
    "¿Qué de tu infancia todavía te influye más de lo que te gustaría?",
    "¿Qué miedo tenés que casi nadie conoce?",
    "¿Qué deseo tenés que te da un poco de vergüenza admitir?",
    "¿Qué vínculo de tu vida marcó cómo amás hoy?",
    "¿Qué significa el amor para vos, más allá de lo que se dice?",
    "¿Qué parte de la intimidad valorás más: la física, la emocional o la mental?",
    "¿Cómo te imaginás en 10 años, sin pensar en nadie más?",
    "¿Qué parte de tu identidad sentís que todavía estás construyendo?",
    "¿Qué recuerdo de tu vida te gustaría poder contarme con lujo de detalle?",
    "¿Qué contradicción tenés que reconocés pero no resolvés?",
    "¿Qué te da más miedo: el compromiso o el abandono?",
    "¿Qué necesitabas de chico/a que no recibiste del todo?",
    "¿Qué es lo más difícil de confiar en alguien para vos?",
    "¿Qué versión tuya del pasado casi no reconocés hoy?",
    "¿Qué cosa nunca te preguntaron y te hubiese gustado que te pregunten?",
    "¿Qué es lo que más te costó perdonar en tu vida?",
    "¿Qué parte de vos cambia cuando estás enamorado/a?",
    "¿Qué creés de vos mismo/a que probablemente no es del todo cierto?",
    "¿Qué necesitás sentir para bajar la guardia con alguien?",
    "¿Qué le dirías a la persona que fuiste hace 5 años?",
    "¿Qué es algo que hacés por costumbre y nunca te preguntaste por qué?",
    "¿Qué es lo que más extrañás de una etapa pasada de tu vida?",
    "¿Qué es algo que aprendiste de una relación anterior que aplicás hoy?",
    "¿Qué es lo que más te gustaría cambiar de tu forma de amar?",
    "¿Qué situación te hace sentir más pequeño/a?",
    "¿Qué situación te hace sentir más poderoso/a?",
    "¿Qué es algo que dijiste una vez y te arrepentís?",
    "¿Qué es algo que no dijiste y te arrepentís?",
    "¿Qué parte de tu cuerpo te costó más aceptar?",
    "¿Qué es algo que creías a los 15 años que hoy te parece ridículo?",
    "¿Qué es algo que te enseñó el dolor que no te enseñó la alegría?",
    "¿Qué persona de tu vida te marcó sin que ella lo sepa?",
    "¿Qué es lo que más te asusta de envejecer?",
    "¿Qué es lo que más te ilusiona de envejecer?",
    "¿Qué es algo que necesitás escuchar más seguido, de cualquier persona?",
    "¿Qué parte de tu personalidad heredaste de alguien de tu familia, para bien o para mal?",
    "¿Qué es algo que perdonaste pero no olvidaste?",
    "¿Qué es algo que no perdonaste pero sí olvidaste, o intentás olvidar?",
    "¿Qué es lo más generoso que hiciste sin que nadie lo supiera?",
    "¿Qué es lo más egoísta que hiciste y todavía te pesa?",
    "¿Qué creencia tenías de chico/a sobre el amor que hoy cuestionás?",
    "¿Qué es algo que te gustaría que supieran de vos sin tener que explicarlo?",
    "¿Qué tan fácil o difícil te resulta pedir ayuda?",
    "¿Qué es algo que te da vergüenza que te guste?",
    "¿Qué es algo que odiás admitir que necesitás?",
    "¿Qué momento de soledad te marcó más en la vida?",
    "¿Qué persona te enseñó, sin querer, cómo NO querés que te traten?",
    "¿Qué es algo que te gustaría perdonarte a vos mismo/a?",
    "¿Qué tan cómodo/a te sentís mostrando tu enojo?",
    "¿Qué es algo que reprimís seguido sin darte cuenta?",
    "¿Qué tipo de amor viste crecer en tu familia, y qué tomaste de ahí?",
    "¿Qué es lo que más te cuesta de estar en pareja, en general?",
    "¿Qué es lo que más disfrutás de estar en pareja, en general?",
    "¿Qué es algo que te gustaría hacer sola/o antes de comprometerte más?",
    "¿Qué es algo de tu forma de ser que te costó aceptar en vos mismo/a?",
    "¿Qué es lo que más valorás cuando alguien te escucha?",
    "¿Qué situación reciente te hizo sentir muy vulnerable?",
    "¿Qué situación reciente te hizo sentir muy fuerte?",
    "¿Qué es algo que te gustaría dejar de necesitar validar en otros?",
    "¿Qué es lo que menos te gusta de pedir perdón?",
    "¿Qué es lo que más te gusta de perdonar a alguien?",
    "¿Qué tan seguido pensás en el futuro versus vivir el presente?",
    "¿Qué es algo que sacrificaste por amor y no te arrepentís?",
    "¿Qué es algo que sacrificaste por amor y sí te arrepentís?",
    "¿Qué te enseñó tu último gran fracaso?",
    "¿Qué te enseñó tu último gran logro?",
    "¿Qué parte de tu rutina diaria dice más de vos de lo que pensás?",
    "¿Qué es algo que te gustaría que la gente notara más en vos?",
    "¿Qué es algo que preferís que la gente no note en vos?",
    "¿Qué tan fácil te resulta confiar en el amor después de una decepción?",
    "¿Qué es algo que aprendiste sobre vos mismo/a en esta relación a distancia?",
    "¿Qué es lo que más te asusta de que esto se vuelva algo cotidiano?",
    "¿Qué es lo que más te ilusiona de que esto se vuelva algo cotidiano?",
    "¿Qué palabra usarías para describir cómo amás?",
    "¿Qué palabra usarías para describir cómo te gustaría que te amen?",
    "¿Qué es algo que necesitás de un vínculo para sentirte en paz?",
    "¿Qué es lo que más te cuesta soltar del pasado?",
    "¿Qué es lo primero que notás en una persona cuando la conocés?",
    "¿Qué es lo último que se te olvida de alguien que ya no está en tu vida?",
    "¿Qué relación (no romántica) marcó tu forma de vincularte con los demás?",
    "¿Qué es algo que hoy te resulta fácil y antes te costaba mucho?",
    "¿Qué es algo que antes te resultaba fácil y hoy te cuesta más?",
    "¿Qué es lo que más admirás de las personas que amás?",
    "¿Qué es algo que te gustaría que tus futuros hijos (si los tenés) sepan de vos?",
    "¿Qué es algo de tu forma de discutir que te gustaría cambiar?",
    "¿Qué es algo de tu forma de discutir de lo que estás orgulloso/a?",
    "¿Qué tanto te cuesta estar solo/a con tus pensamientos?",
    "¿Qué es algo que aprendiste tarde en la vida y te hubiese gustado saber antes?",
    "¿Qué recuerdo de tu adolescencia todavía te da vergüenza?",
    "¿Qué recuerdo de tu adolescencia todavía te da orgullo?",
    "¿Qué es lo que más te costó decirme en esta relación?",
    "¿Qué es algo que todavía no me dijiste porque no encontrás el momento?",
    "¿Qué tan importante es para vos que te digan 'te amo' seguido?",
    "¿Qué gesto pequeño te hace sentir más amado/a que mil palabras?",
    "¿Qué es lo que más te costó de crecer en la familia que te tocó?",
    "¿Qué es lo que más agradecés de la familia que te tocó?",
    "¿Qué es algo que te gustaría reparar con alguien de tu pasado?",
    "¿Qué es algo que ya reparaste con alguien de tu pasado?",
    "¿Qué tan seguido sentís que merecés lo bueno que te pasa?",
    "¿Qué es algo que te cuesta creer sobre vos mismo/a, aunque otros te lo digan?",
    "¿Qué es algo que te gustaría que yo entendiera sin tener que explicarlo cada vez?",
    "¿Qué es algo que descubriste sobre el amor gracias a esta distancia?"
    ]
};
